// <auto-generated />
// =============================================================================
// 20250101000000_InitialCrmSchema.Designer.cs — EF Core Migration Designer
// =============================================================================
// Auto-generated partial class that stores the model snapshot at the time the
// InitialCrmSchema migration was created. EF Core uses this snapshot to compute
// diffs when adding subsequent migrations.
//
// This file defines the complete CRM database model state after the initial
// migration, covering all CRM-owned entities extracted from the monolith:
//   - rec_account   (Entity ID: 2e22b50f-e444-4b62-a171-076e51246939)
//   - rec_contact   (Entity ID: 39e1dd9b-827f-464d-95ea-507ade81cbd0)
//   - rec_case      (Entity ID: 0ebb3981-7443-45c8-ab38-db0709daf58c)
//   - rec_case_status (CRM-owned lookup)
//   - rec_case_type   (CRM-owned lookup)
//   - rec_address   (Entity ID: 34a126ba-1dee-4099-a1c1-a24e70eb10f0)
//   - rec_salutation (Entity ID: 690dc799-e732-4d17-80d8-0f761bc33def)
//   - rel_account_nn_contact  (M:N join table)
//   - rel_account_nn_case     (M:N join table)
//   - rel_address_nn_account  (M:N join table)
//
// Source references:
//   - WebVella.Erp.Plugins.Next/NextPlugin.20190203.cs (case, case_status, case_type, salutation)
//   - WebVella.Erp.Plugins.Next/NextPlugin.20190204.cs (account fields, contact, address, relations)
//   - WebVella.Erp.Plugins.Next/NextPlugin.20190206.cs (salutation rework, audit fields)
//   - WebVella.Erp.Plugins.Crm/CrmPlugin._.cs (CRM patch framework)
//   - WebVella.Erp/Database/DBTypeConverter.cs (ERP→PostgreSQL type mappings)
// =============================================================================

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebVella.Erp.Service.Crm.Database;

#nullable disable

namespace WebVella.Erp.Service.Crm.Database.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20250101000000_InitialCrmSchema")]
    partial class InitialCrmSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            // =================================================================
            // Model-level annotations — Npgsql PostgreSQL provider metadata
            // =================================================================
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            // =================================================================
            // rec_account — Account entity
            // Entity ID: 2e22b50f-e444-4b62-a171-076e51246939
            // Cumulative fields from Patch20190203 + Patch20190204 + Patch20190206
            // =================================================================
            modelBuilder.Entity("rec_account", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("l_scope")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<string>("type")
                    .HasColumnType("text")
                    .HasDefaultValue("company");

                b.Property<string>("website")
                    .HasColumnType("text");

                b.Property<string>("street")
                    .HasColumnType("text");

                b.Property<string>("street_2")
                    .HasColumnType("text");

                b.Property<string>("city")
                    .HasColumnType("text");

                b.Property<string>("region")
                    .HasColumnType("text");

                b.Property<string>("post_code")
                    .HasColumnType("text");

                b.Property<Guid?>("country_id")
                    .HasColumnType("uuid");

                b.Property<string>("fixed_phone")
                    .HasColumnType("text");

                b.Property<string>("mobile_phone")
                    .HasColumnType("text");

                b.Property<string>("fax_phone")
                    .HasColumnType("text");

                b.Property<string>("email")
                    .HasColumnType("text");

                b.Property<string>("notes")
                    .HasColumnType("text");

                b.Property<string>("last_name")
                    .HasColumnType("text");

                b.Property<string>("first_name")
                    .HasColumnType("text");

                b.Property<string>("x_search")
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<string>("tax_id")
                    .HasColumnType("text");

                b.Property<Guid?>("language_id")
                    .HasColumnType("uuid");

                b.Property<Guid?>("currency_id")
                    .HasColumnType("uuid");

                b.Property<Guid?>("salutation_id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("'87c08ee1-8d4d-4c89-9b37-4e3cc3f98698'");

                b.Property<DateTime?>("created_on")
                    .HasColumnType("timestamptz")
                    .HasDefaultValueSql("now()");

                b.Property<Guid?>("created_by")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("last_modified_on")
                    .HasColumnType("timestamptz");

                b.Property<Guid?>("last_modified_by")
                    .HasColumnType("uuid");

                b.HasKey("id");

                b.ToTable("rec_account");
            });

            // =================================================================
            // rec_contact — Contact entity
            // Entity ID: 39e1dd9b-827f-464d-95ea-507ade81cbd0
            // Cumulative fields from Patch20190204 + Patch20190206
            // =================================================================
            modelBuilder.Entity("rec_contact", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<string>("first_name")
                    .HasColumnType("text");

                b.Property<string>("last_name")
                    .HasColumnType("text");

                b.Property<string>("email")
                    .HasColumnType("text");

                b.Property<string>("job_title")
                    .HasColumnType("text");

                b.Property<string>("notes")
                    .HasColumnType("text");

                b.Property<string>("fixed_phone")
                    .HasColumnType("text");

                b.Property<string>("mobile_phone")
                    .HasColumnType("text");

                b.Property<string>("fax_phone")
                    .HasColumnType("text");

                b.Property<string>("city")
                    .HasColumnType("text");

                b.Property<Guid?>("country_id")
                    .HasColumnType("uuid");

                b.Property<string>("region")
                    .HasColumnType("text");

                b.Property<string>("street")
                    .HasColumnType("text");

                b.Property<string>("street_2")
                    .HasColumnType("text");

                b.Property<string>("post_code")
                    .HasColumnType("text");

                b.Property<Guid?>("salutation_id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("'87c08ee1-8d4d-4c89-9b37-4e3cc3f98698'");

                b.Property<string>("photo")
                    .HasColumnType("text");

                b.Property<string>("x_search")
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<DateTime?>("created_on")
                    .HasColumnType("timestamptz")
                    .HasDefaultValueSql("now()");

                b.Property<Guid?>("created_by")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("last_modified_on")
                    .HasColumnType("timestamptz");

                b.Property<Guid?>("last_modified_by")
                    .HasColumnType("uuid");

                b.HasKey("id");

                b.ToTable("rec_contact");
            });

            // =================================================================
            // rec_case — Case entity
            // Entity ID: 0ebb3981-7443-45c8-ab38-db0709daf58c
            // Cumulative fields from Patch20190203 + Patch20190206
            // number field uses PostgreSQL IDENTITY (serial/autonumber)
            // =================================================================
            modelBuilder.Entity("rec_case", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<Guid?>("account_id")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("created_on")
                    .HasColumnType("timestamptz")
                    .HasDefaultValueSql("now()");

                b.Property<Guid?>("created_by")
                    .HasColumnType("uuid");

                b.Property<Guid?>("owner_id")
                    .HasColumnType("uuid");

                b.Property<string>("description")
                    .HasColumnType("text");

                b.Property<string>("subject")
                    .HasColumnType("text");

                b.Property<int>("number")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("number"));

                b.Property<DateTime?>("closed_on")
                    .HasColumnType("timestamptz");

                b.Property<string>("l_scope")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<string>("priority")
                    .HasColumnType("text")
                    .HasDefaultValue("medium");

                b.Property<Guid?>("status_id")
                    .HasColumnType("uuid");

                b.Property<Guid?>("type_id")
                    .HasColumnType("uuid");

                b.Property<string>("x_search")
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<DateTime?>("last_modified_on")
                    .HasColumnType("timestamptz");

                b.Property<Guid?>("last_modified_by")
                    .HasColumnType("uuid");

                b.HasKey("id");

                b.HasIndex("status_id");

                b.HasIndex("type_id");

                b.ToTable("rec_case");
            });

            // =================================================================
            // rec_case_status — Case Status lookup entity (CRM-owned)
            // Referenced by rec_case.status_id via intra-service FK
            // =================================================================
            modelBuilder.Entity("rec_case_status", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<bool>("is_default")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("label")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("sort_index")
                    .HasColumnType("numeric")
                    .HasDefaultValue(0m);

                b.Property<bool>("is_closed")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("is_system")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("is_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<string>("l_scope")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<string>("icon_class")
                    .HasColumnType("text");

                b.Property<string>("color")
                    .HasColumnType("text");

                b.HasKey("id");

                b.ToTable("rec_case_status");
            });

            // =================================================================
            // rec_case_type — Case Type lookup entity (CRM-owned)
            // Referenced by rec_case.type_id via intra-service FK
            // =================================================================
            modelBuilder.Entity("rec_case_type", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<bool>("is_default")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("is_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<bool>("is_system")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("l_scope")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.Property<decimal>("sort_index")
                    .HasColumnType("numeric")
                    .HasDefaultValue(0m);

                b.Property<string>("label")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("icon_class")
                    .HasColumnType("text");

                b.Property<string>("color")
                    .HasColumnType("text");

                b.HasKey("id");

                b.ToTable("rec_case_type");
            });

            // =================================================================
            // rec_address — Address entity
            // Entity ID: 34a126ba-1dee-4099-a1c1-a24e70eb10f0
            // Fields from Patch20190204
            // =================================================================
            modelBuilder.Entity("rec_address", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<string>("name")
                    .HasColumnType("text");

                b.Property<string>("street")
                    .HasColumnType("text");

                b.Property<string>("street_2")
                    .HasColumnType("text");

                b.Property<string>("city")
                    .HasColumnType("text");

                b.Property<string>("region")
                    .HasColumnType("text");

                b.Property<Guid?>("country_id")
                    .HasColumnType("uuid");

                b.Property<string>("notes")
                    .HasColumnType("text");

                b.Property<DateTime?>("created_on")
                    .HasColumnType("timestamptz")
                    .HasDefaultValueSql("now()");

                b.Property<Guid?>("created_by")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("last_modified_on")
                    .HasColumnType("timestamptz");

                b.Property<Guid?>("last_modified_by")
                    .HasColumnType("uuid");

                b.HasKey("id");

                b.ToTable("rec_address");
            });

            // =================================================================
            // rec_salutation — Salutation entity
            // Entity ID: 690dc799-e732-4d17-80d8-0f761bc33def
            // Created in Patch20190206 (replaces old misspelled "solutation")
            // label has unique constraint
            // =================================================================
            modelBuilder.Entity("rec_salutation", b =>
            {
                b.Property<Guid>("id")
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v1()");

                b.Property<bool>("is_default")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<bool>("is_enabled")
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<bool>("is_system")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("label")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("sort_index")
                    .HasColumnType("numeric")
                    .HasDefaultValue(0m);

                b.Property<string>("l_scope")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasDefaultValue("");

                b.HasKey("id");

                b.HasIndex("label")
                    .IsUnique();

                b.ToTable("rec_salutation");
            });

            // =================================================================
            // Many-to-Many Join Tables (shadow entities)
            // =================================================================

            // rel_account_nn_contact — Account ↔ Contact M:N
            // From NextPlugin.20190204 relation definition
            modelBuilder.Entity("rel_account_nn_contact", b =>
            {
                b.Property<Guid>("origin_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("target_id")
                    .HasColumnType("uuid");

                b.HasKey("origin_id", "target_id");

                b.ToTable("rel_account_nn_contact");
            });

            // rel_account_nn_case — Account ↔ Case M:N
            // From NextPlugin.20190204 relation definition
            modelBuilder.Entity("rel_account_nn_case", b =>
            {
                b.Property<Guid>("origin_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("target_id")
                    .HasColumnType("uuid");

                b.HasKey("origin_id", "target_id");

                b.ToTable("rel_account_nn_case");
            });

            // rel_address_nn_account — Address ↔ Account M:N
            // From NextPlugin.20190204 relation definition
            modelBuilder.Entity("rel_address_nn_account", b =>
            {
                b.Property<Guid>("origin_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("target_id")
                    .HasColumnType("uuid");

                b.HasKey("origin_id", "target_id");

                b.ToTable("rel_address_nn_account");
            });

#pragma warning restore 612, 618
        }
    }
}
