using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using FluentAssertions;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Tokens;
using Moq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;
using WebVella.Erp.Service.Admin;
using WebVella.Erp.Service.Admin.Models;
using WebVella.Erp.Service.Admin.Services;
using WebVella.Erp.SharedKernel.Models;

namespace WebVella.Erp.Tests.Admin.Controllers
{
    /// <summary>
    /// Integration tests for the Admin/SDK microservice AdminController REST endpoints.
    /// Uses <see cref="WebApplicationFactory{TEntryPoint}"/> to spin up an in-memory test server
    /// and validates both happy-path and error-path scenarios for every endpoint.
    /// Each test instance creates a fresh factory with isolated mocks (xUnit creates a new class
    /// instance per test method), ensuring zero state leakage between tests.
    /// </summary>
    public class AdminControllerTests : IDisposable
    {
        // ────────────────────────────────────────────────────────────────────────
        // JWT configuration constants — must match the overridden configuration
        // injected into the WebApplicationFactory so generated tokens validate
        // against the same key/issuer/audience as the in-memory test server.
        // ────────────────────────────────────────────────────────────────────────
        private const string JwtTestKey =
            "ThisIsMySecretKeyThisIsMySecretKeyThisIsMySecretKey";
        private const string JwtIssuer = "webvella-erp";
        private const string JwtAudience = "webvella-erp";

        // Well-known test identifiers used across all tests for consistency.
        private static readonly Guid TestUserId =
            Guid.Parse("EABD66FD-8DE1-4D79-9674-447EE89921C2");
        private static readonly Guid TestAppId = Guid.NewGuid();
        private static readonly Guid TestAreaId = Guid.NewGuid();
        private static readonly Guid TestNodeId = Guid.NewGuid();

        // ────────────────────────────────────────────────────────────────────────
        // Mock service instances — one per AdminController DI dependency.
        // Created fresh per test because xUnit instantiates a new class per [Fact].
        // ────────────────────────────────────────────────────────────────────────
        private readonly Mock<IAppService> _mockAppService = new Mock<IAppService>();
        private readonly Mock<IPageService> _mockPageService = new Mock<IPageService>();
        private readonly Mock<IDataSourceManager> _mockDataSourceManager = new Mock<IDataSourceManager>();
        private readonly Mock<IEntityManager> _mockEntityManager = new Mock<IEntityManager>();
        private readonly Mock<IRecordManager> _mockRecordManager = new Mock<IRecordManager>();
        private readonly Mock<ISecurityManager> _mockSecurityManager = new Mock<ISecurityManager>();
        private readonly Mock<IEntityRelationManager> _mockEntityRelationManager = new Mock<IEntityRelationManager>();

        // The in-memory test server wrapping the Admin service pipeline.
        private readonly WebApplicationFactory<Program> _factory;

        /// <summary>
        /// Initializes the test server by creating a <see cref="WebApplicationFactory{TEntryPoint}"/>
        /// configured with mock services and a deterministic JWT signing key.
        /// </summary>
        public AdminControllerTests()
        {
            _factory = new WebApplicationFactory<Program>()
                .WithWebHostBuilder(builder =>
                {
                    // Use "Testing" environment to disable ValidateOnBuild and
                    // avoid infrastructure connectivity requirements (Redis, RabbitMQ, PostgreSQL).
                    builder.UseEnvironment("Testing");

                    // Override JWT configuration with known test values so that tokens
                    // generated by GenerateJwtToken() will pass validation.
                    builder.ConfigureAppConfiguration((context, config) =>
                    {
                        config.AddInMemoryCollection(new Dictionary<string, string>
                        {
                            ["Jwt:Key"] = JwtTestKey,
                            ["Jwt:Issuer"] = JwtIssuer,
                            ["Jwt:Audience"] = JwtAudience,
                        });
                    });

                    builder.ConfigureServices(services =>
                    {
                        // Remove all hosted services to prevent MassTransit bus startup
                        // and background job execution during tests.
                        var hostedDescriptors = services
                            .Where(d => d.ServiceType == typeof(IHostedService))
                            .ToList();
                        foreach (var descriptor in hostedDescriptors)
                        {
                            services.Remove(descriptor);
                        }

                        // Override JWT Bearer token validation parameters.
                        // Program.cs reads the JWT key from configuration at startup
                        // BEFORE ConfigureAppConfiguration overrides take effect,
                        // so we must use PostConfigure to override the already-captured
                        // TokenValidationParameters with our deterministic test key.
                        services.PostConfigure<JwtBearerOptions>(
                            JwtBearerDefaults.AuthenticationScheme,
                            options =>
                            {
                                options.TokenValidationParameters = new TokenValidationParameters
                                {
                                    ValidateIssuer = true,
                                    ValidateAudience = true,
                                    ValidateLifetime = true,
                                    ValidateIssuerSigningKey = true,
                                    ValidIssuer = JwtIssuer,
                                    ValidAudience = JwtAudience,
                                    IssuerSigningKey = new SymmetricSecurityKey(
                                        Encoding.UTF8.GetBytes(JwtTestKey)),
                                    ClockSkew = TimeSpan.FromMinutes(5)
                                };
                            });

                        // Register mock implementations for all AdminController dependencies.
                        // Using AddSingleton ensures the same mock instance is used for all
                        // scoped resolutions within the test server's DI container.
                        services.AddSingleton<IAppService>(_mockAppService.Object);
                        services.AddSingleton<IPageService>(_mockPageService.Object);
                        services.AddSingleton<IDataSourceManager>(_mockDataSourceManager.Object);
                        services.AddSingleton<IEntityManager>(_mockEntityManager.Object);
                        services.AddSingleton<IRecordManager>(_mockRecordManager.Object);
                        services.AddSingleton<ISecurityManager>(_mockSecurityManager.Object);
                        services.AddSingleton<IEntityRelationManager>(_mockEntityRelationManager.Object);
                    });
                });
        }

        /// <summary>
        /// Disposes the <see cref="WebApplicationFactory{TEntryPoint}"/> after each test,
        /// releasing the in-memory test server and all associated resources.
        /// </summary>
        public void Dispose()
        {
            _factory?.Dispose();
        }

        // ════════════════════════════════════════════════════════════════════════
        //  Helper Methods
        // ════════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Generates a signed JWT token compatible with the test server's JWT validation
        /// parameters. The token includes name, identifier, and role claims.
        /// </summary>
        /// <param name="role">The role claim value. Defaults to "administrator" for admin access.</param>
        /// <returns>A serialized JWT token string for use in Authorization: Bearer headers.</returns>
        private string GenerateJwtToken(string role = "administrator")
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JwtTestKey));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            var claims = new[]
            {
                new Claim(ClaimTypes.Name, "testadmin"),
                new Claim(ClaimTypes.NameIdentifier, TestUserId.ToString()),
                new Claim(ClaimTypes.Role, role),
            };

            var token = new JwtSecurityToken(
                issuer: JwtIssuer,
                audience: JwtAudience,
                claims: claims,
                expires: DateTime.UtcNow.AddHours(1),
                signingCredentials: credentials);

            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        /// <summary>
        /// Creates an <see cref="HttpClient"/> with a pre-set Authorization: Bearer header
        /// containing a valid JWT token for the specified role.
        /// </summary>
        /// <param name="role">The role to embed in the JWT. Defaults to "administrator".</param>
        /// <returns>An authenticated HttpClient ready to call protected endpoints.</returns>
        private HttpClient CreateAuthenticatedClient(string role = "administrator")
        {
            var client = _factory.CreateClient();
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", GenerateJwtToken(role));
            return client;
        }

        /// <summary>
        /// Sets up default mock return values for sitemap mutation endpoints.
        /// Configures IAppService.GetApplication, IAppService.OrderSitemap, and
        /// IPageService.GetNodePageDictionary to return valid objects so that
        /// happy-path tests pass through the entire controller logic.
        /// </summary>
        /// <param name="appId">The application ID used in mock setups.</param>
        private void SetupSitemapSuccessMocks(Guid appId)
        {
            var sitemap = new Sitemap
            {
                Areas = new List<SitemapArea>
                {
                    new SitemapArea { Id = TestAreaId, Name = "test-area", Label = "Test Area" }
                }
            };
            var appState = new AppState
            {
                Id = appId,
                Name = "test-app",
                Label = "Test App",
                Sitemap = sitemap
            };

            _mockAppService
                .Setup(x => x.GetApplication(It.IsAny<Guid>()))
                .Returns(appState);
            _mockAppService
                .Setup(x => x.OrderSitemap(It.IsAny<Sitemap>()))
                .Returns<Sitemap>(s => s);
            _mockPageService
                .Setup(x => x.GetNodePageDictionary(It.IsAny<Guid?>()))
                .Returns(new Dictionary<Guid, List<Guid>>());
        }

        /// <summary>
        /// Serializes an object to a JSON <see cref="StringContent"/> using Newtonsoft.Json
        /// for backward-compatible [JsonProperty] annotation handling.
        /// </summary>
        private static StringContent ToJsonContent(object obj)
        {
            var json = JsonConvert.SerializeObject(obj);
            return new StringContent(json, Encoding.UTF8, "application/json");
        }

        // ════════════════════════════════════════════════════════════════════════
        //  DataSource Endpoint Tests
        //  GET api/v3.0/p/sdk/datasource/list
        // ════════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Verifies that an authenticated GET to the datasource list endpoint returns
        /// HTTP 200 with data sources sorted alphabetically by Name.
        /// </summary>
        [Fact]
        public async Task DataSourceList_Authenticated_ReturnsSortedDataSources()
        {
            // Arrange — return unsorted list from mock
            _mockDataSourceManager
                .Setup(x => x.GetAll())
                .Returns(new List<DataSourceBase>
                {
                    new DatabaseDataSource { Name = "Zebra" },
                    new DatabaseDataSource { Name = "Alpha" },
                    new DatabaseDataSource { Name = "Middle" },
                });
            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.GetAsync("api/v3.0/p/sdk/datasource/list");

            // Assert — HTTP 200 and alphabetical sort
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var dsArray = JArray.Parse(json);
            dsArray.Should().HaveCount(3);
            var names = dsArray.Select(ds => (string)ds["name"]).ToList();
            names.Should().BeInAscendingOrder();
            names[0].Should().Be("Alpha");
            names[1].Should().Be("Middle");
            names[2].Should().Be("Zebra");
        }

        /// <summary>
        /// Verifies that a GET without an Authorization header returns HTTP 401 Unauthorized.
        /// </summary>
        [Fact]
        public async Task DataSourceList_Unauthenticated_Returns401()
        {
            // Arrange — no auth header
            var client = _factory.CreateClient();

            // Act
            var response = await client.GetAsync("api/v3.0/p/sdk/datasource/list");

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
        }

        // ════════════════════════════════════════════════════════════════════════
        //  Sitemap Area CRUD Tests
        //  POST api/v3.0/p/sdk/sitemap/area
        //  POST api/v3.0/p/sdk/sitemap/area/{areaId}
        //  POST api/v3.0/p/sdk/sitemap/area/{areaId}/delete
        // ════════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Verifies that creating a sitemap area with valid input returns success=true
        /// with the response containing sitemap and node_page_dict keys.
        /// </summary>
        [Fact]
        public async Task CreateSitemapArea_ValidInput_ReturnsSuccessWithSitemap()
        {
            // Arrange
            SetupSitemapSuccessMocks(TestAppId);
            var area = new SitemapArea
            {
                Id = Guid.NewGuid(),
                Name = "new-area",
                Label = "New Area",
                IconClass = "fa fa-folder",
                Weight = 1,
                Access = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area?appId={TestAppId}",
                ToJsonContent(area));

            // Assert — success envelope with sitemap and node_page_dict
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();
            jObj["message"].Value<string>().Should().Be("Success");
            jObj["object"].Should().NotBeNull();
            jObj["object"]["sitemap"].Should().NotBeNull();
            jObj["object"]["node_page_dict"].Should().NotBeNull();
            jObj["timestamp"].Should().NotBeNull();
            jObj["errors"].Should().NotBeNull();
        }

        /// <summary>
        /// Verifies that posting a null body to CreateSitemapArea returns success=false
        /// with the exact backward-compatible error message.
        /// </summary>
        [Fact]
        public async Task CreateSitemapArea_NullBody_ReturnsFailure()
        {
            // Arrange
            var client = CreateAuthenticatedClient();
            var nullContent = new StringContent("null", Encoding.UTF8, "application/json");

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area?appId={TestAppId}",
                nullContent);

            // Assert — HTTP 200 with error payload (not 400)
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Wrong object model submitted. Could not restore!");
        }

        /// <summary>
        /// Verifies that omitting the appId query string returns success=false
        /// with the exact backward-compatible error message.
        /// </summary>
        [Fact]
        public async Task CreateSitemapArea_MissingAppId_ReturnsFailure()
        {
            // Arrange — valid body but NO appId query string
            var area = new SitemapArea
            {
                Id = Guid.NewGuid(),
                Name = "area",
                Label = "Area"
            };
            var client = CreateAuthenticatedClient();

            // Act — no ?appId= parameter
            var response = await client.PostAsync(
                "api/v3.0/p/sdk/sitemap/area",
                ToJsonContent(area));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Application Id needs to be submitted as 'appId' query string");
        }

        /// <summary>
        /// Verifies that a user with a non-administrator role receives HTTP 403 Forbidden.
        /// </summary>
        [Fact]
        public async Task CreateSitemapArea_NonAdminRole_Returns403()
        {
            // Arrange — authenticated with "regular" role (not administrator)
            var area = new SitemapArea { Id = Guid.NewGuid(), Name = "area", Label = "Area" };
            var client = CreateAuthenticatedClient("regular");

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area?appId={TestAppId}",
                ToJsonContent(area));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.Forbidden);
        }

        /// <summary>
        /// Verifies that updating a sitemap area with valid input returns success=true
        /// with sitemap and node_page_dict in the response object.
        /// </summary>
        [Fact]
        public async Task UpdateSitemapArea_ValidInput_ReturnsSuccessWithSitemap()
        {
            // Arrange
            var areaId = Guid.NewGuid();
            SetupSitemapSuccessMocks(TestAppId);
            var area = new SitemapArea
            {
                Id = areaId,
                Name = "updated-area",
                Label = "Updated Area",
                IconClass = "fa fa-star",
                Weight = 2,
                Access = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act — POST to area/{areaId}
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area/{areaId}?appId={TestAppId}",
                ToJsonContent(area));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();
            jObj["message"].Value<string>().Should().Be("Success");
            jObj["object"]["sitemap"].Should().NotBeNull();
            jObj["object"]["node_page_dict"].Should().NotBeNull();
        }

        /// <summary>
        /// Verifies that updating with Guid.Empty area ID returns the exact error message.
        /// </summary>
        [Fact]
        public async Task UpdateSitemapArea_EmptyAreaId_ReturnsFailure()
        {
            // Arrange — area with Id = Guid.Empty
            var area = new SitemapArea
            {
                Id = Guid.Empty,
                Name = "area",
                Label = "Area"
            };
            var client = CreateAuthenticatedClient();

            // Act — the URL areaId doesn't matter; the controller checks body area.Id
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area/{Guid.NewGuid()}?appId={TestAppId}",
                ToJsonContent(area));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should().Be("Area Id needs to be submitted");
        }

        /// <summary>
        /// Verifies that deleting a sitemap area with valid input returns success=true
        /// with sitemap and node_page_dict.
        /// </summary>
        [Fact]
        public async Task DeleteSitemapArea_ValidInput_ReturnsSuccessWithSitemap()
        {
            // Arrange
            var areaId = Guid.NewGuid();
            SetupSitemapSuccessMocks(TestAppId);
            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area/{areaId}/delete?appId={TestAppId}",
                new StringContent("", Encoding.UTF8, "application/json"));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();
            jObj["object"]["sitemap"].Should().NotBeNull();
            jObj["object"]["node_page_dict"].Should().NotBeNull();
        }

        /// <summary>
        /// Verifies that deleting with Guid.Empty area ID returns the exact error message.
        /// </summary>
        [Fact]
        public async Task DeleteSitemapArea_EmptyAreaId_ReturnsFailure()
        {
            // Arrange
            var client = CreateAuthenticatedClient();

            // Act — areaId = Guid.Empty in the URL
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/area/{Guid.Empty}/delete?appId={TestAppId}",
                new StringContent("", Encoding.UTF8, "application/json"));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should().Be("Area Id needs to be submitted");
        }

        // ════════════════════════════════════════════════════════════════════════
        //  Sitemap Node CRUD Tests
        //  POST api/v3.0/p/sdk/sitemap/node
        //  POST api/v3.0/p/sdk/sitemap/node/{nodeId}
        //  POST api/v3.0/p/sdk/sitemap/node/{nodeId}/delete
        // ════════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Verifies that creating a sitemap node with valid input (including page attachment)
        /// returns success=true with sitemap and node_page_dict in the response.
        /// </summary>
        [Fact]
        public async Task CreateSitemapNode_ValidInput_ReturnsSuccessWithSitemap()
        {
            // Arrange — configure all required mock behaviors
            var areaId = Guid.NewGuid();
            var pageId = Guid.NewGuid();
            SetupSitemapSuccessMocks(TestAppId);

            // Mock page retrieval for the page attachment loop in CreateSitemapNode
            var testPage = new ErpPage
            {
                Id = pageId,
                Name = "TestPage",
                Label = "Test Page",
                Type = PageType.Application,
                AppId = TestAppId,
                NodeId = null
            };
            _mockPageService
                .Setup(x => x.GetPage(pageId))
                .Returns(testPage);

            var node = new SitemapNodeSubmit
            {
                Id = Guid.NewGuid(),
                Name = "new-node",
                Label = "New Node",
                IconClass = "fa fa-file",
                Url = "",
                Type = SitemapNodeType.ApplicationPage,
                EntityId = null,
                Weight = 1,
                Access = new List<Guid>(),
                ParentId = null,
                Pages = new List<Guid> { pageId }
            };
            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node?appId={TestAppId}&areaId={areaId}",
                ToJsonContent(node));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();
            jObj["message"].Value<string>().Should().Be("Success");
            jObj["object"]["sitemap"].Should().NotBeNull();
            jObj["object"]["node_page_dict"].Should().NotBeNull();
        }

        /// <summary>
        /// Verifies that posting a null body to CreateSitemapNode returns the exact error message.
        /// </summary>
        [Fact]
        public async Task CreateSitemapNode_NullBody_ReturnsFailure()
        {
            // Arrange
            var client = CreateAuthenticatedClient();
            var nullContent = new StringContent("null", Encoding.UTF8, "application/json");

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node?appId={TestAppId}&areaId={Guid.NewGuid()}",
                nullContent);

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Wrong object model submitted. Could not restore!");
        }

        /// <summary>
        /// Verifies that omitting the appId query string for node creation returns the exact error.
        /// </summary>
        [Fact]
        public async Task CreateSitemapNode_MissingAppId_ReturnsFailure()
        {
            // Arrange
            var node = new SitemapNodeSubmit
            {
                Id = Guid.NewGuid(),
                Name = "node",
                Label = "Node",
                Pages = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act — no appId in query string
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node?areaId={Guid.NewGuid()}",
                ToJsonContent(node));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Application Id needs to be submitted as 'appId' query string");
        }

        /// <summary>
        /// Verifies that omitting the areaId query string for node creation returns the exact error.
        /// </summary>
        [Fact]
        public async Task CreateSitemapNode_MissingAreaId_ReturnsFailure()
        {
            // Arrange
            var node = new SitemapNodeSubmit
            {
                Id = Guid.NewGuid(),
                Name = "node",
                Label = "Node",
                Pages = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act — has appId but no areaId
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node?appId={TestAppId}",
                ToJsonContent(node));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Area Id needs to be submitted as 'areaId' query string");
        }

        /// <summary>
        /// Verifies that updating a sitemap node with valid input (including page attach/detach)
        /// returns success=true with sitemap and node_page_dict.
        /// The test verifies both page attachment (new pages) and detachment (removed pages)
        /// behavior by checking mock invocations.
        /// </summary>
        [Fact]
        public async Task UpdateSitemapNode_ValidInput_ReturnsSuccessWithSitemap()
        {
            // Arrange
            var nodeId = Guid.NewGuid();
            var areaId = Guid.NewGuid();
            var existingPageId = Guid.NewGuid();
            var newPageId = Guid.NewGuid();
            SetupSitemapSuccessMocks(TestAppId);

            // Existing attached page (will be detached because it's NOT in the new Pages list)
            var existingPage = new ErpPage
            {
                Id = existingPageId,
                Name = "ExistingPage",
                Type = PageType.Application,
                AppId = TestAppId,
                NodeId = nodeId,
                AreaId = areaId
            };

            // New page to attach (currently unattached)
            var newPage = new ErpPage
            {
                Id = newPageId,
                Name = "NewPage",
                Type = PageType.Application,
                AppId = TestAppId,
                NodeId = null
            };

            _mockPageService
                .Setup(x => x.GetAppControlledPages(It.IsAny<Guid>()))
                .Returns(new List<ErpPage> { existingPage });
            _mockPageService
                .Setup(x => x.GetPage(newPageId))
                .Returns(newPage);
            _mockPageService
                .Setup(x => x.GetPage(existingPageId))
                .Returns(existingPage);

            var node = new SitemapNodeSubmit
            {
                Id = nodeId,
                Name = "updated-node",
                Label = "Updated Node",
                IconClass = "fa fa-edit",
                Url = "",
                Type = SitemapNodeType.ApplicationPage,
                EntityId = null,
                Weight = 2,
                Access = new List<Guid>(),
                ParentId = null,
                Pages = new List<Guid> { newPageId } // Only newPageId; existingPageId is dropped
            };
            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{nodeId}?appId={TestAppId}&areaId={areaId}",
                ToJsonContent(node));

            // Assert — success response
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();
            jObj["message"].Value<string>().Should().Be("Success");
            jObj["object"]["sitemap"].Should().NotBeNull();
            jObj["object"]["node_page_dict"].Should().NotBeNull();

            // Verify that UpdatePage was called for both detached and attached pages
            _mockPageService.Verify(
                x => x.UpdatePage(It.IsAny<ErpPage>()),
                Times.AtLeastOnce());
        }

        /// <summary>
        /// Verifies that updating with Guid.Empty node ID in the body returns the exact error.
        /// </summary>
        [Fact]
        public async Task UpdateSitemapNode_EmptyNodeId_ReturnsFailure()
        {
            // Arrange — node.Id = Guid.Empty triggers the validation
            var node = new SitemapNodeSubmit
            {
                Id = Guid.Empty,
                Name = "node",
                Label = "Node",
                Pages = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act — appId and areaId provided so earlier checks pass
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{Guid.NewGuid()}?appId={TestAppId}&areaId={Guid.NewGuid()}",
                ToJsonContent(node));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should().Be("Node Id needs to be submitted");
        }

        /// <summary>
        /// Verifies that omitting appId when updating a node returns the exact error.
        /// </summary>
        [Fact]
        public async Task UpdateSitemapNode_MissingAppId_ReturnsFailure()
        {
            // Arrange
            var node = new SitemapNodeSubmit
            {
                Id = Guid.NewGuid(),
                Name = "node",
                Label = "Node",
                Pages = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act — areaId provided but no appId
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{node.Id}?areaId={Guid.NewGuid()}",
                ToJsonContent(node));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Application Id needs to be submitted as 'appId' query string");
        }

        /// <summary>
        /// Verifies that omitting areaId when updating a node returns the exact error.
        /// </summary>
        [Fact]
        public async Task UpdateSitemapNode_MissingAreaId_ReturnsFailure()
        {
            // Arrange
            var node = new SitemapNodeSubmit
            {
                Id = Guid.NewGuid(),
                Name = "node",
                Label = "Node",
                Pages = new List<Guid>()
            };
            var client = CreateAuthenticatedClient();

            // Act — appId provided but no areaId
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{node.Id}?appId={TestAppId}",
                ToJsonContent(node));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Area Id needs to be submitted as 'areaId' query string");
        }

        /// <summary>
        /// Verifies that deleting a sitemap node with valid input returns success=true.
        /// </summary>
        [Fact]
        public async Task DeleteSitemapNode_ValidInput_ReturnsSuccessWithSitemap()
        {
            // Arrange
            var nodeId = Guid.NewGuid();
            SetupSitemapSuccessMocks(TestAppId);
            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{nodeId}/delete?appId={TestAppId}",
                new StringContent("", Encoding.UTF8, "application/json"));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();
            jObj["object"]["sitemap"].Should().NotBeNull();
            jObj["object"]["node_page_dict"].Should().NotBeNull();
        }

        /// <summary>
        /// Verifies that deleting with Guid.Empty node ID returns the exact error.
        /// </summary>
        [Fact]
        public async Task DeleteSitemapNode_EmptyNodeId_ReturnsFailure()
        {
            // Arrange
            var client = CreateAuthenticatedClient();

            // Act — nodeId = Guid.Empty in URL
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{Guid.Empty}/delete?appId={TestAppId}",
                new StringContent("", Encoding.UTF8, "application/json"));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should().Be("Node Id needs to be submitted");
        }

        /// <summary>
        /// Verifies that omitting the appId query string for node deletion returns the exact error.
        /// </summary>
        [Fact]
        public async Task DeleteSitemapNode_MissingAppId_ReturnsFailure()
        {
            // Arrange
            var nodeId = Guid.NewGuid();
            var client = CreateAuthenticatedClient();

            // Act — valid nodeId but no appId
            var response = await client.PostAsync(
                $"api/v3.0/p/sdk/sitemap/node/{nodeId}/delete",
                new StringContent("", Encoding.UTF8, "application/json"));

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Application Id needs to be submitted as 'appId' query string");
        }

        // ════════════════════════════════════════════════════════════════════════
        //  Node Auxiliary Data Tests
        //  GET api/v3.0/p/sdk/sitemap/node/get-aux-info
        // ════════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Verifies that GetNodeAuxData with a valid appId returns the full auxiliary data
        /// structure including all_entities (sorted SelectOptions with "not attached" sentinel
        /// at index 0), node_types (sorted SelectOptions from SitemapNodeType enum),
        /// app_pages (application pages with no node assignment), and all_entity_pages
        /// (pages with non-null EntityId matching the given appId).
        /// </summary>
        [Fact]
        public async Task GetNodeAuxData_ValidAppId_ReturnsEntityOptionsAndNodeTypes()
        {
            // Arrange
            var entityId1 = Guid.NewGuid();
            var entityId2 = Guid.NewGuid();
            var pageId1 = Guid.NewGuid();
            var pageId2 = Guid.NewGuid();
            var pageId3 = Guid.NewGuid();

            // Mock ReadEntities — return two entities
            // NOTE: The controller uses entity.Name (NOT entity.Label) for SelectOption.Label
            var entityListResponse = new EntityListResponse
            {
                Success = true,
                Object = new List<Entity>
                {
                    new Entity { Id = entityId1, Name = "account", Label = "Account" },
                    new Entity { Id = entityId2, Name = "contact", Label = "Contact" }
                }
            };
            _mockEntityManager
                .Setup(x => x.ReadEntities())
                .Returns(entityListResponse);

            // Mock GetAppControlledPages — pages with AppId matching; used for app_pages
            var controlledPages = new List<ErpPage>
            {
                new ErpPage
                {
                    Id = pageId1,
                    Name = "Dashboard",
                    Type = PageType.Application,
                    AppId = TestAppId,
                    NodeId = null // unattached → should appear in app_pages
                },
                new ErpPage
                {
                    Id = pageId2,
                    Name = "AccountList",
                    Type = PageType.RecordList,
                    AppId = TestAppId,
                    NodeId = TestNodeId // attached → should NOT appear in app_pages
                }
            };
            _mockPageService
                .Setup(x => x.GetAppControlledPages(It.IsAny<Guid>()))
                .Returns(controlledPages);

            // Mock GetAllPages — all pages in the system; used for all_entity_pages
            var allPages = new List<ErpPage>
            {
                new ErpPage
                {
                    Id = pageId2,
                    Name = "AccountList",
                    Type = PageType.RecordList,
                    AppId = TestAppId,
                    EntityId = entityId1,
                    NodeId = TestNodeId
                },
                new ErpPage
                {
                    Id = pageId3,
                    Name = "ContactDetails",
                    Type = PageType.RecordDetails,
                    AppId = TestAppId,
                    EntityId = entityId2,
                    NodeId = null
                },
                // Page from a different app — should NOT appear in all_entity_pages
                new ErpPage
                {
                    Id = Guid.NewGuid(),
                    Name = "OtherAppPage",
                    Type = PageType.RecordList,
                    AppId = Guid.NewGuid(),
                    EntityId = entityId1,
                    NodeId = null
                }
            };
            _mockPageService
                .Setup(x => x.GetAllPages())
                .Returns(allPages);

            var client = CreateAuthenticatedClient();

            // Act
            var response = await client.GetAsync(
                $"api/v3.0/p/sdk/sitemap/node/get-aux-info?appId={TestAppId}");

            // Assert — full structure validation
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeTrue();

            var responseObj = jObj["object"];
            responseObj.Should().NotBeNull();

            // ── all_entities ──
            // Controller sorts entities by entity.Name, then inserts "not attached"
            // sentinel at index 0. So index 0 is always "not attached", and remaining
            // items are sorted alphabetically by entity.Name.
            var allEntities = (JArray)responseObj["all_entities"];
            allEntities.Should().NotBeNull();
            allEntities.Count.Should().Be(3); // "not attached" + 2 entities

            // Index 0: "not attached" sentinel with Value = ""
            var firstOption = allEntities[0];
            ((string)firstOption["label"]).Should().Be("not attached");
            ((string)firstOption["value"]).Should().Be("");

            // Remaining items (index 1+) should be sorted by label (entity.Name)
            var sortedEntityLabels = allEntities.Skip(1)
                .Select(e => (string)e["label"]).ToList();
            sortedEntityLabels.Should().BeInAscendingOrder();
            sortedEntityLabels.Should().Contain("account");
            sortedEntityLabels.Should().Contain("contact");

            // ── node_types ──
            // Should contain all SitemapNodeType enum values sorted by label
            var nodeTypes = (JArray)responseObj["node_types"];
            nodeTypes.Should().NotBeNull();
            nodeTypes.Count.Should().Be(3); // EntityList, ApplicationPage, Url
            var nodeTypeLabels = nodeTypes.Select(n => (string)n["label"]).ToList();
            nodeTypeLabels.Should().BeInAscendingOrder();
            // Verify known labels from SitemapNodeType enum [SelectOption] attributes
            nodeTypeLabels.Should().Contain("application page");
            nodeTypeLabels.Should().Contain("entity list");
            nodeTypeLabels.Should().Contain("url");

            // ── app_pages ──
            // Only Application-type pages with NodeId == null, ordered by page.Name
            var appPages = (JArray)responseObj["app_pages"];
            appPages.Should().NotBeNull();
            appPages.Count.Should().Be(1); // Only "Dashboard" matches
            var firstAppPage = appPages[0];
            ((string)firstAppPage["page_name"]).Should().Be("Dashboard");
            firstAppPage["page_id"].Should().NotBeNull();
            // node_id is stored as empty string "" for null NodeId (controller behavior)
            ((string)firstAppPage["node_id"]).Should().Be("");

            // ── all_entity_pages ──
            // Pages with non-null EntityId and matching AppId, sorted by page_name.
            // Controller stores type as string ((int)page.Type).ToString() and
            // node_id as string (empty string when null).
            var allEntityPages = (JArray)responseObj["all_entity_pages"];
            allEntityPages.Should().NotBeNull();
            allEntityPages.Count.Should().Be(2); // AccountList and ContactDetails (same app)
            var entityPageNames = allEntityPages
                .Select(p => (string)p["page_name"]).ToList();
            entityPageNames.Should().BeInAscendingOrder();
            entityPageNames.Should().Contain("AccountList");
            entityPageNames.Should().Contain("ContactDetails");
            // Verify structure of entity page records
            var accountListPage = allEntityPages.First(
                p => (string)p["page_name"] == "AccountList");
            accountListPage["entity_id"].Should().NotBeNull();
            accountListPage["type"].Should().NotBeNull();
            accountListPage["page_id"].Should().NotBeNull();
            // type should be string representation of RecordList int value
            ((string)accountListPage["type"]).Should().Be(((int)PageType.RecordList).ToString());
        }

        /// <summary>
        /// Verifies that omitting the appId query string for GetNodeAuxData
        /// returns the exact error message.
        /// </summary>
        [Fact]
        public async Task GetNodeAuxData_MissingAppId_ReturnsFailure()
        {
            // Arrange
            var client = CreateAuthenticatedClient();

            // Act — no appId query string
            var response = await client.GetAsync(
                "api/v3.0/p/sdk/sitemap/node/get-aux-info");

            // Assert
            response.StatusCode.Should().Be(HttpStatusCode.OK);
            var json = await response.Content.ReadAsStringAsync();
            var jObj = JObject.Parse(json);
            jObj["success"].Value<bool>().Should().BeFalse();
            jObj["message"].Value<string>().Should()
                .Be("Application Id needs to be submitted as 'appId' query string");
        }
    }
}
