using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebVella.Erp.Service.Project.Database
{
    // =========================================================================
    // Entity Model Classes — mapped to monolith rec_* tables
    // =========================================================================

    /// <summary>
    /// Represents a task record in the Project/Task microservice.
    /// Maps to the monolith's rec_task table, preserving all columns and
    /// application-set Guid primary keys (ValueGeneratedNever).
    /// Cross-service references (OwnerId, CreatedBy) are stored as plain UUIDs
    /// without foreign key constraints per AAP 0.7.1.
    /// </summary>
    [Table("rec_task")]
    public class TaskEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Task subject/title — required field in the monolith.</summary>
        [Required]
        [Column("subject")]
        public string Subject { get; set; }

        /// <summary>HTML body content of the task.</summary>
        [Column("body")]
        public string Body { get; set; }

        /// <summary>
        /// Cross-service reference to the user who owns this task.
        /// Stored as UUID — NO FK constraint. Resolved via Core gRPC call.
        /// </summary>
        [Column("owner_id")]
        public Guid? OwnerId { get; set; }

        /// <summary>Task start date (nullable).</summary>
        [Column("start_date")]
        public DateTime? StartDate { get; set; }

        /// <summary>Task target/due date (nullable).</summary>
        [Column("target_date")]
        public DateTime? TargetDate { get; set; }

        /// <summary>Timestamp when the task was created.</summary>
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Cross-service reference to the user who created this task.
        /// Stored as UUID — NO FK constraint.
        /// </summary>
        [Column("created_by")]
        public Guid? CreatedBy { get; set; }

        /// <summary>Timestamp when the task was completed (nullable).</summary>
        [Column("completed_on")]
        public DateTime? CompletedOn { get; set; }

        /// <summary>
        /// Auto-incremented task number within scope.
        /// Stored as bigint in PostgreSQL.
        /// </summary>
        [Column("number")]
        public long Number { get; set; }

        /// <summary>Self-referencing parent task ID for task hierarchies.</summary>
        [Column("parent_id")]
        public Guid? ParentId { get; set; }

        /// <summary>FK to task_status entity — intra-service relation.</summary>
        [Column("status_id")]
        public Guid? StatusId { get; set; }

        /// <summary>FK to task_type entity — intra-service relation.</summary>
        [Column("type_id")]
        public Guid? TypeId { get; set; }

        /// <summary>
        /// Priority select field. Values: "1" (low), "2" (medium), "3" (high).
        /// Stored as text to match monolith SelectField behavior.
        /// </summary>
        [Column("priority")]
        public string Priority { get; set; }

        /// <summary>
        /// Aggregated non-billable time in minutes for this task.
        /// Monolith column: x_nonbillable_minutes (NumberField, decimal).
        /// </summary>
        [Column("x_nonbillable_minutes")]
        public decimal XNonbillableHours { get; set; }

        /// <summary>
        /// Aggregated billable time in minutes for this task.
        /// Monolith column: x_billable_minutes (NumberField, decimal).
        /// </summary>
        [Column("x_billable_minutes")]
        public decimal XBillableHours { get; set; }

        /// <summary>
        /// Scope identifier for multi-tenant/multi-project scoping.
        /// JSON array string, e.g. '["projects"]'.
        /// </summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>
        /// JSON-encoded list of related record references.
        /// Used for cross-entity linking within the project domain.
        /// </summary>
        [Column("l_related_records")]
        public string LRelatedRecords { get; set; }

        /// <summary>
        /// Full-text search index field. Regenerated by SearchService
        /// to include denormalized data from related entities.
        /// </summary>
        [Column("x_search")]
        public string XSearch { get; set; }

        /// <summary>Reference to a recurrence plan (Ical.Net based).</summary>
        [Column("recurrence_id")]
        public Guid? RecurrenceId { get; set; }

        /// <summary>
        /// Human-readable task key (e.g., "PRJ-123").
        /// Composed from project abbreviation + task number.
        /// </summary>
        [Column("key")]
        public string Key { get; set; }

        // ----- Navigation properties (intra-service) -----

        /// <summary>Navigation to the task's status reference entity.</summary>
        public TaskStatusEntity Status { get; set; }

        /// <summary>Navigation to the task's type reference entity.</summary>
        public TaskTypeEntity Type { get; set; }

        /// <summary>Navigation to parent task (self-referencing).</summary>
        public TaskEntity Parent { get; set; }

        /// <summary>Child tasks in the task hierarchy.</summary>
        public ICollection<TaskEntity> Children { get; set; } = new List<TaskEntity>();

        /// <summary>M:N relation entries linking milestones to this task.</summary>
        public ICollection<MilestoneTaskRelation> MilestoneTaskRelations { get; set; } = new List<MilestoneTaskRelation>();

        /// <summary>M:N relation entries linking projects to this task.</summary>
        public ICollection<ProjectTaskRelation> ProjectTaskRelations { get; set; } = new List<ProjectTaskRelation>();
    }

    /// <summary>
    /// Represents a timelog record for time tracking against tasks.
    /// Maps to the monolith's rec_timelog table.
    /// </summary>
    [Table("rec_timelog")]
    public class TimelogEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Body/description of the time entry.</summary>
        [Column("body")]
        public string Body { get; set; }

        /// <summary>Cross-service user reference — NO FK constraint.</summary>
        [Column("created_by")]
        public Guid? CreatedBy { get; set; }

        /// <summary>Timestamp when the timelog was created.</summary>
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }

        /// <summary>JSON-encoded related record references.</summary>
        [Column("l_related_records")]
        public string LRelatedRecords { get; set; }

        /// <summary>Scope identifier for multi-project scoping.</summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>Duration in minutes logged for this entry.</summary>
        [Column("minutes")]
        public decimal Minutes { get; set; }

        /// <summary>Whether this time entry is billable.</summary>
        [Column("is_billable")]
        public bool IsBillable { get; set; }
    }

    /// <summary>
    /// Represents a comment record attached to tasks or other entities.
    /// Maps to the monolith's rec_comment table.
    /// </summary>
    [Table("rec_comment")]
    public class CommentEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Comment text/body content.</summary>
        [Column("body")]
        public string Body { get; set; }

        /// <summary>Cross-service user reference — NO FK constraint.</summary>
        [Column("created_by")]
        public Guid? CreatedBy { get; set; }

        /// <summary>Timestamp when the comment was created.</summary>
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }

        /// <summary>Scope identifier for multi-project scoping.</summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>JSON-encoded related record references.</summary>
        [Column("l_related_records")]
        public string LRelatedRecords { get; set; }

        /// <summary>Self-referencing parent comment ID for nested comments.</summary>
        [Column("parent_id")]
        public Guid? ParentId { get; set; }
    }

    /// <summary>
    /// Represents an activity feed item in the project domain.
    /// Maps to the monolith's rec_feed_item table.
    /// Feed items track task, timelog, and comment activity.
    /// </summary>
    [Table("rec_feed_item")]
    public class FeedItemEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Cross-service user reference — NO FK constraint.</summary>
        [Column("created_by")]
        public Guid? CreatedBy { get; set; }

        /// <summary>Timestamp when the feed item was created.</summary>
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }

        /// <summary>Scope identifier for multi-project scoping.</summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>Feed item subject/title.</summary>
        [Column("subject")]
        public string Subject { get; set; }

        /// <summary>Feed item body/content.</summary>
        [Column("body")]
        public string Body { get; set; }

        /// <summary>
        /// Feed item type discriminator.
        /// Values: "task", "timelog", "comment" (select field in monolith).
        /// </summary>
        [Column("type")]
        public string Type { get; set; }

        /// <summary>JSON-encoded related record references.</summary>
        [Column("l_related_records")]
        public string LRelatedRecords { get; set; }
    }

    /// <summary>
    /// Represents a project record in the Project/Task microservice.
    /// Maps to the monolith's rec_project table.
    /// Contains aggregated statistics (x_ fields) that are updated by
    /// domain services when tasks, timelogs, or milestones change.
    /// </summary>
    [Table("rec_project")]
    public class ProjectEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Project name — required field.</summary>
        [Required]
        [Column("name")]
        public string Name { get; set; }

        /// <summary>
        /// Project abbreviation used in task key generation (e.g., "PRJ").
        /// Required field.
        /// </summary>
        [Required]
        [Column("abbr")]
        public string Abbr { get; set; }

        /// <summary>Project description (HTML content).</summary>
        [Column("description")]
        public string Description { get; set; }

        /// <summary>
        /// Cross-service reference to the project owner user.
        /// Stored as UUID — NO FK constraint. Resolved via Core gRPC.
        /// </summary>
        [Column("owner_id")]
        public Guid? OwnerId { get; set; }

        /// <summary>Project color for UI display (hex, e.g., "#9c27b0").</summary>
        [Column("color")]
        public string Color { get; set; }

        /// <summary>Project icon CSS class (e.g., "fas fa-cogs").</summary>
        [Column("icon")]
        public string Icon { get; set; }

        /// <summary>Project start date.</summary>
        [Column("start_date")]
        public DateTime? StartDate { get; set; }

        /// <summary>Project end date.</summary>
        [Column("end_date")]
        public DateTime? EndDate { get; set; }

        /// <summary>Whether time entries on this project are billable by default.</summary>
        [Column("is_billable")]
        public bool IsBillable { get; set; }

        /// <summary>
        /// Scope key used for scoped queries and multi-project filtering.
        /// </summary>
        [Column("scope_key")]
        public string ScopeKey { get; set; }

        /// <summary>Aggregated billable hours/minutes across all project tasks.</summary>
        [Column("x_billable_hours")]
        public decimal XBillableHours { get; set; }

        /// <summary>Aggregated non-billable hours/minutes across all project tasks.</summary>
        [Column("x_nonbillable_hours")]
        public decimal XNonbillableHours { get; set; }

        /// <summary>Count of tasks in "Not Started" status.</summary>
        [Column("x_tasks_not_started")]
        public int XTasksNotStarted { get; set; }

        /// <summary>Count of tasks in "In Progress" status.</summary>
        [Column("x_tasks_in_progress")]
        public int XTasksInProgress { get; set; }

        /// <summary>Count of tasks in "Completed" status.</summary>
        [Column("x_tasks_completed")]
        public int XTasksCompleted { get; set; }

        /// <summary>Count of overdue tasks (past target_date, not completed).</summary>
        [Column("x_overdue_tasks")]
        public int XOverdueTasks { get; set; }

        /// <summary>Count of milestones currently on track.</summary>
        [Column("x_milestones_on_track")]
        public int XMilestonesOnTrack { get; set; }

        /// <summary>Count of milestones that have been missed.</summary>
        [Column("x_milestones_missed")]
        public int XMilestonesMissed { get; set; }

        /// <summary>Project budget amount (decimal with precision 18,3).</summary>
        [Column("x_budget")]
        public decimal XBudget { get; set; }
    }

    /// <summary>
    /// Represents a task type reference entity (e.g., General, Call, Email, Bug).
    /// Maps to the monolith's rec_task_type table.
    /// Seeded with deterministic GUIDs from monolith patch NextPlugin.20190203.
    /// </summary>
    [Table("rec_task_type")]
    public class TaskTypeEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Display label for the task type.</summary>
        [Required]
        [Column("label")]
        public string Label { get; set; }

        /// <summary>Font Awesome icon CSS class.</summary>
        [Column("icon_class")]
        public string IconClass { get; set; }

        /// <summary>Sort order for display in UI dropdowns.</summary>
        [Column("sort_index")]
        public int SortOrder { get; set; }

        /// <summary>Whether this is the default task type for new tasks.</summary>
        [Column("is_default")]
        public bool IsDefault { get; set; }

        /// <summary>Scope identifier for scoped visibility.</summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>Display color (hex string, e.g., "#F44336").</summary>
        [Column("color")]
        public string Color { get; set; }

        /// <summary>Whether this task type is enabled and available for selection.</summary>
        [Column("is_enabled")]
        public bool IsEnabled { get; set; }

        /// <summary>Whether this is a system-defined task type that cannot be deleted.</summary>
        [Column("is_system")]
        public bool IsSystem { get; set; }
    }

    /// <summary>
    /// Represents a task status reference entity (e.g., Not Started, In Progress, Completed).
    /// Maps to the monolith's rec_task_status table.
    /// Seeded with deterministic GUIDs from monolith patch NextPlugin.20190203.
    /// </summary>
    [Table("rec_task_status")]
    public class TaskStatusEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Display label for the task status.</summary>
        [Required]
        [Column("label")]
        public string Label { get; set; }

        /// <summary>Font Awesome icon CSS class.</summary>
        [Column("icon_class")]
        public string IconClass { get; set; }

        /// <summary>Sort order for display in UI dropdowns.</summary>
        [Column("sort_index")]
        public int SortOrder { get; set; }

        /// <summary>Whether this is the default status for new tasks.</summary>
        [Column("is_default")]
        public bool IsDefault { get; set; }

        /// <summary>Scope identifier for scoped visibility.</summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>Display color (hex string).</summary>
        [Column("color")]
        public string Color { get; set; }

        /// <summary>Whether this task status is enabled and available for selection.</summary>
        [Column("is_enabled")]
        public bool IsEnabled { get; set; }

        /// <summary>
        /// Whether this status represents a closed/completed state.
        /// Used to determine if tasks with this status are "done".
        /// </summary>
        [Column("is_closed")]
        public bool IsClosed { get; set; }

        /// <summary>Whether this is a system-defined task status that cannot be deleted.</summary>
        [Column("is_system")]
        public bool IsSystem { get; set; }
    }

    /// <summary>
    /// Represents a milestone record in the project domain.
    /// Maps to the monolith's rec_milestone table.
    /// Milestones group tasks and track project progress checkpoints.
    /// </summary>
    [Table("rec_milestone")]
    public class MilestoneEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Milestone name — required field.</summary>
        [Required]
        [Column("name")]
        public string Name { get; set; }

        /// <summary>Milestone start date.</summary>
        [Column("start_date")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// Milestone end/target date.
        /// Monolith column: target_date (DateTimeField).
        /// </summary>
        [Column("end_date")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Milestone status. Values: "on_track", "missed", "completed".
        /// </summary>
        [Column("status")]
        public string Status { get; set; }
    }

    // =========================================================================
    // Join Entity Classes — mapped to monolith rel_* tables for M:N relations
    // =========================================================================

    /// <summary>
    /// Join entity for the many-to-many relationship between Project and Task.
    /// Maps to the monolith's rel_project_nn_task table.
    /// Composite primary key: (OriginId, TargetId) where OriginId=project, TargetId=task.
    /// </summary>
    [Table("rel_project_nn_task")]
    public class ProjectTaskRelation
    {
        /// <summary>Project ID (origin side of the M:N relation).</summary>
        [Column("origin_id")]
        public Guid OriginId { get; set; }

        /// <summary>Task ID (target side of the M:N relation).</summary>
        [Column("target_id")]
        public Guid TargetId { get; set; }

        /// <summary>Navigation to the project entity.</summary>
        public ProjectEntity Project { get; set; }

        /// <summary>Navigation to the task entity.</summary>
        public TaskEntity Task { get; set; }
    }

    /// <summary>
    /// Join entity for the many-to-many relationship between Milestone and Task.
    /// Maps to the monolith's rel_milestone_nn_task table.
    /// Composite primary key: (OriginId, TargetId) where OriginId=milestone, TargetId=task.
    /// </summary>
    [Table("rel_milestone_nn_task")]
    public class MilestoneTaskRelation
    {
        /// <summary>Milestone ID (origin side of the M:N relation).</summary>
        [Column("origin_id")]
        public Guid OriginId { get; set; }

        /// <summary>Task ID (target side of the M:N relation).</summary>
        [Column("target_id")]
        public Guid TargetId { get; set; }

        /// <summary>Navigation to the milestone entity.</summary>
        public MilestoneEntity Milestone { get; set; }

        /// <summary>Navigation to the task entity.</summary>
        public TaskEntity Task { get; set; }
    }

    /// <summary>
    /// Join entity for the many-to-many relationship between Project and Milestone.
    /// Maps to the monolith's rel_project_nn_milestone table.
    /// Composite primary key: (OriginId, TargetId) where OriginId=project, TargetId=milestone.
    /// </summary>
    [Table("rel_project_nn_milestone")]
    public class ProjectMilestoneRelation
    {
        /// <summary>Project ID (origin side of the M:N relation).</summary>
        [Column("origin_id")]
        public Guid OriginId { get; set; }

        /// <summary>Milestone ID (target side of the M:N relation).</summary>
        [Column("target_id")]
        public Guid TargetId { get; set; }

        /// <summary>Navigation to the project entity.</summary>
        public ProjectEntity Project { get; set; }

        /// <summary>Navigation to the milestone entity.</summary>
        public MilestoneEntity Milestone { get; set; }
    }

    /// <summary>
    /// Join entity for the many-to-many relationship between Comment and Attachment.
    /// Maps to the monolith's rel_comment_nn_attachment table.
    /// Composite primary key: (OriginId, TargetId) where OriginId=comment, TargetId=attachment.
    /// Note: Attachment entity is owned by the Core service (user_file);
    /// TargetId references core attachment UUID without FK constraint.
    /// </summary>
    [Table("rel_comment_nn_attachment")]
    public class CommentAttachmentRelation
    {
        /// <summary>Comment ID (origin side of the M:N relation).</summary>
        [Column("origin_id")]
        public Guid OriginId { get; set; }

        /// <summary>Attachment ID (target side — cross-service ref, NO FK).</summary>
        [Column("target_id")]
        public Guid TargetId { get; set; }
    }

    // =========================================================================
    // ProjectDbContext — EF Core DbContext for the Project/Task Microservice
    // =========================================================================

    /// <summary>
    /// EF Core DbContext for the Project/Task microservice, implementing the
    /// database-per-service pattern. This replaces the monolith's ambient
    /// <c>WebVella.Erp.Database.DbContext</c> singleton (AsyncLocal + ConcurrentDictionary)
    /// with a proper DI-scoped DbContext per AAP 0.7.2.
    ///
    /// Key design decisions:
    /// <list type="bullet">
    ///   <item>All entity Guid PKs use ValueGeneratedNever (application-set, matching monolith)</item>
    ///   <item>Cross-service references (user IDs, account IDs) stored as plain UUIDs without FK</item>
    ///   <item>Table names preserve monolith conventions: rec_* for entities, rel_* for join tables</item>
    ///   <item>Column names use PostgreSQL snake_case matching original rec_* table columns</item>
    ///   <item>Seed data uses exact GUIDs from monolith patch files for data integrity</item>
    /// </list>
    ///
    /// Registration in DI (Program.cs):
    /// <code>
    /// builder.Services.AddDbContext&lt;ProjectDbContext&gt;(options =>
    ///     options.UseNpgsql(connectionString));
    /// </code>
    /// </summary>
    public class ProjectDbContext : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectDbContext"/> class
        /// using the standard EF Core DI constructor pattern.
        /// </summary>
        /// <param name="options">
        /// Database context options configured via DI, including the Npgsql provider
        /// connection string with pooling settings (MinPoolSize=1, MaxPoolSize=100).
        /// </param>
        public ProjectDbContext(DbContextOptions<ProjectDbContext> options) : base(options)
        {
        }

        // ----- DbSet Properties for Record Entities -----

        /// <summary>Tasks in the project domain (rec_task).</summary>
        public DbSet<TaskEntity> Tasks { get; set; }

        /// <summary>Time log entries (rec_timelog).</summary>
        public DbSet<TimelogEntity> Timelogs { get; set; }

        /// <summary>Comments attached to tasks and other entities (rec_comment).</summary>
        public DbSet<CommentEntity> Comments { get; set; }

        /// <summary>Activity feed items (rec_feed_item).</summary>
        public DbSet<FeedItemEntity> FeedItems { get; set; }

        /// <summary>Projects (rec_project).</summary>
        public DbSet<ProjectEntity> Projects { get; set; }

        /// <summary>Task type reference data (rec_task_type).</summary>
        public DbSet<TaskTypeEntity> TaskTypes { get; set; }

        /// <summary>Task status reference data (rec_task_status).</summary>
        public DbSet<TaskStatusEntity> TaskStatuses { get; set; }

        /// <summary>Milestones (rec_milestone).</summary>
        public DbSet<MilestoneEntity> Milestones { get; set; }

        // ----- DbSet Properties for Join Tables -----

        /// <summary>Project ↔ Task M:N relation (rel_project_nn_task).</summary>
        public DbSet<ProjectTaskRelation> ProjectTaskRelations { get; set; }

        /// <summary>Milestone ↔ Task M:N relation (rel_milestone_nn_task).</summary>
        public DbSet<MilestoneTaskRelation> MilestoneTaskRelations { get; set; }

        /// <summary>Project ↔ Milestone M:N relation (rel_project_nn_milestone).</summary>
        public DbSet<ProjectMilestoneRelation> ProjectMilestoneRelations { get; set; }

        /// <summary>Comment ↔ Attachment M:N relation (rel_comment_nn_attachment).</summary>
        public DbSet<CommentAttachmentRelation> CommentAttachmentRelations { get; set; }

        /// <summary>
        /// Configures the entity model using EF Core Fluent API.
        /// Establishes table mappings, primary keys, relationships, column types,
        /// and seed data for the Project/Task microservice database.
        /// </summary>
        /// <param name="modelBuilder">The model builder provided by EF Core.</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // =================================================================
            // TaskEntity Configuration
            // =================================================================
            modelBuilder.Entity<TaskEntity>(entity =>
            {
                entity.ToTable("rec_task");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Subject)
                    .HasColumnName("subject")
                    .IsRequired();

                entity.Property(e => e.Body)
                    .HasColumnName("body");

                entity.Property(e => e.OwnerId)
                    .HasColumnName("owner_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.StartDate)
                    .HasColumnName("start_date")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.TargetDate)
                    .HasColumnName("target_date")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.CreatedOn)
                    .HasColumnName("created_on")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.CreatedBy)
                    .HasColumnName("created_by")
                    .HasColumnType("uuid");

                entity.Property(e => e.CompletedOn)
                    .HasColumnName("completed_on")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.Number)
                    .HasColumnName("number");

                entity.Property(e => e.ParentId)
                    .HasColumnName("parent_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.StatusId)
                    .HasColumnName("status_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.TypeId)
                    .HasColumnName("type_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.Priority)
                    .HasColumnName("priority");

                entity.Property(e => e.XNonbillableHours)
                    .HasColumnName("x_nonbillable_minutes")
                    .HasPrecision(18, 3);

                entity.Property(e => e.XBillableHours)
                    .HasColumnName("x_billable_minutes")
                    .HasPrecision(18, 3);

                entity.Property(e => e.LScope)
                    .HasColumnName("l_scope");

                entity.Property(e => e.LRelatedRecords)
                    .HasColumnName("l_related_records");

                entity.Property(e => e.XSearch)
                    .HasColumnName("x_search");

                entity.Property(e => e.RecurrenceId)
                    .HasColumnName("recurrence_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.Key)
                    .HasColumnName("key");

                // Intra-service FK: Task → TaskStatus (1:N)
                entity.HasOne(t => t.Status)
                    .WithMany()
                    .HasForeignKey(t => t.StatusId)
                    .OnDelete(DeleteBehavior.SetNull);

                // Intra-service FK: Task → TaskType (1:N)
                entity.HasOne(t => t.Type)
                    .WithMany()
                    .HasForeignKey(t => t.TypeId)
                    .OnDelete(DeleteBehavior.SetNull);

                // Self-referencing: Task → Parent Task
                entity.HasOne(t => t.Parent)
                    .WithMany(t => t.Children)
                    .HasForeignKey(t => t.ParentId)
                    .OnDelete(DeleteBehavior.SetNull);
            });

            // =================================================================
            // TimelogEntity Configuration
            // =================================================================
            modelBuilder.Entity<TimelogEntity>(entity =>
            {
                entity.ToTable("rec_timelog");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Body)
                    .HasColumnName("body");

                entity.Property(e => e.CreatedBy)
                    .HasColumnName("created_by")
                    .HasColumnType("uuid");

                entity.Property(e => e.CreatedOn)
                    .HasColumnName("created_on")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.LRelatedRecords)
                    .HasColumnName("l_related_records");

                entity.Property(e => e.LScope)
                    .HasColumnName("l_scope");

                entity.Property(e => e.Minutes)
                    .HasColumnName("minutes")
                    .HasPrecision(18, 3);

                entity.Property(e => e.IsBillable)
                    .HasColumnName("is_billable")
                    .HasColumnType("boolean");
            });

            // =================================================================
            // CommentEntity Configuration
            // =================================================================
            modelBuilder.Entity<CommentEntity>(entity =>
            {
                entity.ToTable("rec_comment");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Body)
                    .HasColumnName("body");

                entity.Property(e => e.CreatedBy)
                    .HasColumnName("created_by")
                    .HasColumnType("uuid");

                entity.Property(e => e.CreatedOn)
                    .HasColumnName("created_on")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.LScope)
                    .HasColumnName("l_scope");

                entity.Property(e => e.LRelatedRecords)
                    .HasColumnName("l_related_records");

                entity.Property(e => e.ParentId)
                    .HasColumnName("parent_id")
                    .HasColumnType("uuid");
            });

            // =================================================================
            // FeedItemEntity Configuration
            // =================================================================
            modelBuilder.Entity<FeedItemEntity>(entity =>
            {
                entity.ToTable("rec_feed_item");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.CreatedBy)
                    .HasColumnName("created_by")
                    .HasColumnType("uuid");

                entity.Property(e => e.CreatedOn)
                    .HasColumnName("created_on")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.LScope)
                    .HasColumnName("l_scope");

                entity.Property(e => e.Subject)
                    .HasColumnName("subject");

                entity.Property(e => e.Body)
                    .HasColumnName("body");

                entity.Property(e => e.Type)
                    .HasColumnName("type");

                entity.Property(e => e.LRelatedRecords)
                    .HasColumnName("l_related_records");
            });

            // =================================================================
            // ProjectEntity Configuration
            // =================================================================
            modelBuilder.Entity<ProjectEntity>(entity =>
            {
                entity.ToTable("rec_project");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .IsRequired();

                entity.Property(e => e.Abbr)
                    .HasColumnName("abbr")
                    .IsRequired();

                entity.Property(e => e.Description)
                    .HasColumnName("description");

                entity.Property(e => e.OwnerId)
                    .HasColumnName("owner_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.Color)
                    .HasColumnName("color");

                entity.Property(e => e.Icon)
                    .HasColumnName("icon");

                entity.Property(e => e.StartDate)
                    .HasColumnName("start_date")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.EndDate)
                    .HasColumnName("end_date")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.IsBillable)
                    .HasColumnName("is_billable")
                    .HasColumnType("boolean");

                entity.Property(e => e.ScopeKey)
                    .HasColumnName("scope_key");

                entity.Property(e => e.XBillableHours)
                    .HasColumnName("x_billable_hours")
                    .HasPrecision(18, 3);

                entity.Property(e => e.XNonbillableHours)
                    .HasColumnName("x_nonbillable_hours")
                    .HasPrecision(18, 3);

                entity.Property(e => e.XTasksNotStarted)
                    .HasColumnName("x_tasks_not_started");

                entity.Property(e => e.XTasksInProgress)
                    .HasColumnName("x_tasks_in_progress");

                entity.Property(e => e.XTasksCompleted)
                    .HasColumnName("x_tasks_completed");

                entity.Property(e => e.XOverdueTasks)
                    .HasColumnName("x_overdue_tasks");

                entity.Property(e => e.XMilestonesOnTrack)
                    .HasColumnName("x_milestones_on_track");

                entity.Property(e => e.XMilestonesMissed)
                    .HasColumnName("x_milestones_missed");

                entity.Property(e => e.XBudget)
                    .HasColumnName("x_budget")
                    .HasPrecision(18, 3);
            });

            // =================================================================
            // TaskTypeEntity Configuration
            // =================================================================
            modelBuilder.Entity<TaskTypeEntity>(entity =>
            {
                entity.ToTable("rec_task_type");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Label)
                    .HasColumnName("label")
                    .IsRequired();

                entity.Property(e => e.IconClass)
                    .HasColumnName("icon_class");

                entity.Property(e => e.SortOrder)
                    .HasColumnName("sort_index");

                entity.Property(e => e.IsDefault)
                    .HasColumnName("is_default")
                    .HasColumnType("boolean");

                entity.Property(e => e.LScope)
                    .HasColumnName("l_scope");

                entity.Property(e => e.Color)
                    .HasColumnName("color");

                entity.Property(e => e.IsEnabled)
                    .HasColumnName("is_enabled")
                    .HasColumnType("boolean");

                entity.Property(e => e.IsSystem)
                    .HasColumnName("is_system")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                // Seed data from monolith NextPlugin.20190203.cs (exact GUIDs preserved)
                entity.HasData(
                    new TaskTypeEntity
                    {
                        Id = new Guid("da9bf72d-3655-4c51-9f99-047ef9297bf2"),
                        Label = "General",
                        IsDefault = true,
                        LScope = "",
                        SortOrder = 1,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("7b191135-5fbb-4db9-bf24-1a5fc72d8cd5"),
                        Label = "Call",
                        IsDefault = false,
                        LScope = "",
                        SortOrder = 2,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("489b16e1-91b1-4a05-b247-50ed74f7aaaf"),
                        Label = "Email",
                        IsDefault = false,
                        LScope = "",
                        SortOrder = 3,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("894ba1ef-1b31-440c-9b33-f301d047d8fb"),
                        Label = "Meeting",
                        IsDefault = false,
                        LScope = "",
                        SortOrder = 4,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("ddb9c170-706d-4b17-a8ee-78ed3a544fa3"),
                        Label = "Send Quote",
                        IsDefault = false,
                        LScope = "",
                        SortOrder = 5,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("6105dcf4-4115-435f-94bb-0190d45d1b87"),
                        Label = "Improvement",
                        IsDefault = false,
                        LScope = "[\"projects\"]",
                        SortOrder = 2,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = "far fa-fw fa-caret-square-up",
                        Color = "#9C27B0"
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("a0465e9f-5d5f-433d-acf1-1da0eaec78b4"),
                        Label = "New Feature",
                        IsDefault = true,
                        LScope = "[\"projects\"]",
                        SortOrder = 1,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = "fas fa-fw fa-plus-square",
                        Color = "#4CAF50"
                    },
                    new TaskTypeEntity
                    {
                        Id = new Guid("c0a2554c-f59a-434e-be00-217a416f8efd"),
                        Label = "Bug",
                        IsDefault = false,
                        LScope = "[\"projects\"]",
                        SortOrder = 3,
                        IsEnabled = true,
                        IsSystem = true,
                        IconClass = "fas fa-fw fa-bug",
                        Color = "#F44336"
                    }
                );
            });

            // =================================================================
            // TaskStatusEntity Configuration
            // =================================================================
            modelBuilder.Entity<TaskStatusEntity>(entity =>
            {
                entity.ToTable("rec_task_status");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Label)
                    .HasColumnName("label")
                    .IsRequired();

                entity.Property(e => e.IconClass)
                    .HasColumnName("icon_class");

                entity.Property(e => e.SortOrder)
                    .HasColumnName("sort_index");

                entity.Property(e => e.IsDefault)
                    .HasColumnName("is_default")
                    .HasColumnType("boolean");

                entity.Property(e => e.LScope)
                    .HasColumnName("l_scope");

                entity.Property(e => e.Color)
                    .HasColumnName("color");

                entity.Property(e => e.IsEnabled)
                    .HasColumnName("is_enabled")
                    .HasColumnType("boolean");

                entity.Property(e => e.IsClosed)
                    .HasColumnName("is_closed")
                    .HasColumnType("boolean");

                entity.Property(e => e.IsSystem)
                    .HasColumnName("is_system")
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                // Seed data from monolith NextPlugin.20190203.cs (exact GUIDs preserved)
                entity.HasData(
                    new TaskStatusEntity
                    {
                        Id = new Guid("f3fdd750-0c16-4215-93b3-5373bd528d1f"),
                        Label = "Not Started",
                        IsClosed = false,
                        IsDefault = true,
                        IsSystem = true,
                        LScope = "",
                        SortOrder = 1,
                        IsEnabled = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskStatusEntity
                    {
                        Id = new Guid("20d73f63-3501-4565-a55e-2d291549a9bd"),
                        Label = "In Progress",
                        IsClosed = false,
                        IsDefault = false,
                        IsSystem = true,
                        LScope = "",
                        SortOrder = 2,
                        IsEnabled = true,
                        IconClass = null,
                        Color = null
                    },
                    new TaskStatusEntity
                    {
                        Id = new Guid("b1cc69e5-ce09-40e0-8785-b6452b257bdf"),
                        Label = "Completed",
                        IsClosed = true,
                        IsDefault = false,
                        IsSystem = true,
                        LScope = "",
                        SortOrder = 4,
                        IsEnabled = true,
                        IconClass = "",
                        Color = ""
                    },
                    new TaskStatusEntity
                    {
                        Id = new Guid("8b2aa2af-17dd-400a-a221-78ee744c4866"),
                        Label = "Blocked",
                        IsClosed = false,
                        IsDefault = false,
                        IsSystem = true,
                        LScope = "",
                        SortOrder = 3,
                        IsEnabled = true,
                        IconClass = "",
                        Color = ""
                    },
                    new TaskStatusEntity
                    {
                        Id = new Guid("a1e527fd-4472-4b39-a1d4-af4905d2310c"),
                        Label = "Rejected",
                        IsClosed = true,
                        IsDefault = false,
                        IsSystem = true,
                        LScope = "",
                        SortOrder = 5,
                        IsEnabled = true,
                        IconClass = "",
                        Color = ""
                    }
                );
            });

            // =================================================================
            // MilestoneEntity Configuration
            // =================================================================
            modelBuilder.Entity<MilestoneEntity>(entity =>
            {
                entity.ToTable("rec_milestone");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("uuid")
                    .ValueGeneratedNever();

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .IsRequired();

                entity.Property(e => e.StartDate)
                    .HasColumnName("start_date")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.EndDate)
                    .HasColumnName("end_date")
                    .HasColumnType("timestamptz");

                entity.Property(e => e.Status)
                    .HasColumnName("status");
            });

            // =================================================================
            // M:N Join Table Configurations
            // =================================================================

            // ProjectTaskRelation: Project ↔ Task (M:N)
            modelBuilder.Entity<ProjectTaskRelation>(entity =>
            {
                entity.ToTable("rel_project_nn_task");
                entity.HasKey(e => new { e.OriginId, e.TargetId });

                entity.Property(e => e.OriginId)
                    .HasColumnName("origin_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.TargetId)
                    .HasColumnName("target_id")
                    .HasColumnType("uuid");

                entity.HasOne(e => e.Project)
                    .WithMany()
                    .HasForeignKey(e => e.OriginId)
                    .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(e => e.Task)
                    .WithMany(t => t.ProjectTaskRelations)
                    .HasForeignKey(e => e.TargetId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // MilestoneTaskRelation: Milestone ↔ Task (M:N)
            modelBuilder.Entity<MilestoneTaskRelation>(entity =>
            {
                entity.ToTable("rel_milestone_nn_task");
                entity.HasKey(e => new { e.OriginId, e.TargetId });

                entity.Property(e => e.OriginId)
                    .HasColumnName("origin_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.TargetId)
                    .HasColumnName("target_id")
                    .HasColumnType("uuid");

                entity.HasOne(e => e.Milestone)
                    .WithMany()
                    .HasForeignKey(e => e.OriginId)
                    .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(e => e.Task)
                    .WithMany(t => t.MilestoneTaskRelations)
                    .HasForeignKey(e => e.TargetId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // ProjectMilestoneRelation: Project ↔ Milestone (M:N)
            modelBuilder.Entity<ProjectMilestoneRelation>(entity =>
            {
                entity.ToTable("rel_project_nn_milestone");
                entity.HasKey(e => new { e.OriginId, e.TargetId });

                entity.Property(e => e.OriginId)
                    .HasColumnName("origin_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.TargetId)
                    .HasColumnName("target_id")
                    .HasColumnType("uuid");

                entity.HasOne(e => e.Project)
                    .WithMany()
                    .HasForeignKey(e => e.OriginId)
                    .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(e => e.Milestone)
                    .WithMany()
                    .HasForeignKey(e => e.TargetId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // CommentAttachmentRelation: Comment ↔ Attachment (M:N)
            // Note: TargetId references Core service attachment — NO FK constraint
            modelBuilder.Entity<CommentAttachmentRelation>(entity =>
            {
                entity.ToTable("rel_comment_nn_attachment");
                entity.HasKey(e => new { e.OriginId, e.TargetId });

                entity.Property(e => e.OriginId)
                    .HasColumnName("origin_id")
                    .HasColumnType("uuid");

                entity.Property(e => e.TargetId)
                    .HasColumnName("target_id")
                    .HasColumnType("uuid");

                // OriginId references Comment — local FK
                // TargetId references Core service attachment — NO FK constraint
            });
        }
    }
}
