// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebVella.Erp.Service.Admin.Database;

#nullable disable

namespace WebVella.Erp.Service.Admin.Database.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebVella.Erp.Service.Admin.Database.JobEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AbortedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("aborted_by");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<Guid?>("CanceledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("canceled_by");

                    b.Property<string>("CompleteClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complete_class_name");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finished_on");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_on")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<Guid?>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id");

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_jobs_created_on")
                        .IsDescending(true);

                    b.HasIndex("SchedulePlanId")
                        .HasDatabaseName("ix_jobs_schedule_plan_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.HasIndex("Priority", "CreatedOn")
                        .HasDatabaseName("ix_jobs_priority_created_on");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("WebVella.Erp.Service.Admin.Database.PluginDataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_data_name");

                    b.ToTable("plugin_data");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a61c4949-6b5c-44e6-94b5-e145b0b4c022"),
                            Data = "{\"Version\":20210429}",
                            Name = "sdk"
                        });
                });

            modelBuilder.Entity("WebVella.Erp.Service.Admin.Database.SchedulePlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("EndTimespan")
                        .HasColumnType("integer")
                        .HasColumnName("end_timespan");

                    b.Property<int?>("IntervalInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_in_minutes");

                    b.Property<string>("JobAttributes")
                        .HasColumnType("text")
                        .HasColumnName("job_attributes");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_on")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LastStartedJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_started_job_id");

                    b.Property<DateTime?>("LastTriggerTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_trigger_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextTriggerTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_trigger_time");

                    b.Property<string>("ScheduledDays")
                        .HasColumnType("text")
                        .HasColumnName("schedule_days");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("StartTimespan")
                        .HasColumnType("integer")
                        .HasColumnName("start_timespan");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_schedule_plans_name");

                    b.HasIndex("Enabled", "NextTriggerTime")
                        .HasDatabaseName("ix_schedule_plans_enabled_next_trigger");

                    b.ToTable("schedule_plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cc1df20-0967-4635-b44a-45fd90819105"),
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            IntervalInMinutes = 1440,
                            JobTypeId = new Guid("99d9a8bb-31e6-4436-b0c2-20bd6aa23786"),
                            LastModifiedOn = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clear job and error logs.",
                            ScheduledDays = "{\"scheduled_on_sunday\":true,\"scheduled_on_monday\":true,\"scheduled_on_tuesday\":true,\"scheduled_on_wednesday\":true,\"scheduled_on_thursday\":true,\"scheduled_on_friday\":true,\"scheduled_on_saturday\":true}",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 2, DateTimeKind.Utc),
                            StartTimespan = 0,
                            EndTimespan = 1440,
                            Type = 2
                        });
                });

            modelBuilder.Entity("WebVella.Erp.Service.Admin.Database.SystemLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("message");

                    b.Property<int>("NotificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("notification_status");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("source");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_system_log_created_on")
                        .IsDescending(true);

                    b.ToTable("system_log");
                });
#pragma warning restore 612, 618
        }
    }
}
