// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebVella.Erp.Service.Mail.Database;

#nullable disable

namespace WebVella.Erp.Service.Mail.Database.Migrations
{
    [DbContext(typeof(MailDbContext))]
    partial class MailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebVella.Erp.Service.Mail.Database.Email", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Attachments")
                    .IsRequired()
                    .HasDefaultValue("[]")
                    .HasColumnType("text")
                    .HasColumnName("attachments");

                b.Property<string>("ContentHtml")
                    .HasColumnType("text")
                    .HasColumnName("content_html");

                b.Property<string>("ContentText")
                    .HasColumnType("text")
                    .HasColumnName("content_text");

                b.Property<DateTime>("CreatedOn")
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_on");

                b.Property<string>("Priority")
                    .IsRequired()
                    .HasDefaultValue("1")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("priority");

                b.Property<string>("Recipients")
                    .IsRequired()
                    .HasDefaultValue("")
                    .HasColumnType("text")
                    .HasColumnName("recipients");

                b.Property<string>("ReplyToEmail")
                    .HasColumnType("text")
                    .HasColumnName("reply_to_email");

                b.Property<decimal>("RetriesCount")
                    .HasDefaultValue(0m)
                    .HasColumnType("numeric")
                    .HasColumnName("retries_count");

                b.Property<DateTime?>("ScheduledOn")
                    .HasColumnType("timestamptz")
                    .HasColumnName("scheduled_on");

                b.Property<string>("Sender")
                    .IsRequired()
                    .HasDefaultValue("[]")
                    .HasColumnType("text")
                    .HasColumnName("sender");

                b.Property<DateTime?>("SentOn")
                    .HasColumnType("timestamptz")
                    .HasColumnName("sent_on");

                b.Property<string>("ServerError")
                    .HasColumnType("text")
                    .HasColumnName("server_error");

                b.Property<Guid>("ServiceId")
                    .HasColumnType("uuid")
                    .HasColumnName("service_id");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasDefaultValue("0")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("status");

                b.Property<string>("Subject")
                    .HasMaxLength(1000)
                    .HasColumnType("text")
                    .HasColumnName("subject");

                b.Property<string>("XSearch")
                    .IsRequired()
                    .HasDefaultValue("")
                    .HasColumnType("text")
                    .HasColumnName("x_search");

                b.HasKey("Id");

                b.HasIndex("CreatedOn")
                    .HasDatabaseName("idx_rec_email_created_on");

                b.HasIndex("Priority")
                    .HasDatabaseName("idx_rec_email_priority");

                b.HasIndex("Recipients")
                    .HasDatabaseName("idx_rec_email_recipients");

                b.HasIndex("ScheduledOn")
                    .HasDatabaseName("idx_rec_email_scheduled_on");

                b.HasIndex("Sender")
                    .HasDatabaseName("idx_rec_email_sender");

                b.HasIndex("SentOn")
                    .HasDatabaseName("idx_rec_email_sent_on");

                b.HasIndex("ServiceId")
                    .HasDatabaseName("idx_rec_email_service_id");

                b.HasIndex("XSearch")
                    .HasDatabaseName("idx_rec_email_x_search");

                b.ToTable("rec_email");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Mail.Database.SmtpServiceEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("ConnectionSecurity")
                    .IsRequired()
                    .HasDefaultValue("1")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("connection_security");

                b.Property<string>("DefaultReplyToEmail")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)")
                    .HasColumnName("default_reply_to_email");

                b.Property<string>("DefaultSenderEmail")
                    .IsRequired()
                    .HasDefaultValue("")
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)")
                    .HasColumnName("default_sender_email");

                b.Property<string>("DefaultSenderName")
                    .HasColumnType("text")
                    .HasColumnName("default_sender_name");

                b.Property<bool>("IsDefault")
                    .HasDefaultValue(false)
                    .HasColumnType("boolean")
                    .HasColumnName("is_default");

                b.Property<bool>("IsEnabled")
                    .HasDefaultValue(true)
                    .HasColumnType("boolean")
                    .HasColumnName("is_enabled");

                b.Property<decimal>("MaxRetriesCount")
                    .HasDefaultValue(3m)
                    .HasColumnType("numeric")
                    .HasColumnName("max_retries_count");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<string>("Password")
                    .HasColumnType("text")
                    .HasColumnName("password");

                b.Property<decimal>("Port")
                    .HasDefaultValue(25m)
                    .HasColumnType("numeric")
                    .HasColumnName("port");

                b.Property<decimal>("RetryWaitMinutes")
                    .HasDefaultValue(60m)
                    .HasColumnType("numeric")
                    .HasColumnName("retry_wait_minutes");

                b.Property<string>("Server")
                    .IsRequired()
                    .HasDefaultValue("smtp.domain.com")
                    .HasColumnType("text")
                    .HasColumnName("server");

                b.Property<string>("Username")
                    .HasColumnType("text")
                    .HasColumnName("username");

                b.HasKey("Id");

                b.HasIndex("DefaultSenderEmail")
                    .HasDatabaseName("idx_rec_smtp_service_default_sender_email");

                b.HasIndex("DefaultSenderName")
                    .HasDatabaseName("idx_rec_smtp_service_default_sender_name");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("idx_rec_smtp_service_name");

                b.ToTable("rec_smtp_service");
            });
#pragma warning restore 612, 618
        }
    }
}
