// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebVella.Erp.Service.Reporting.Database;

#nullable disable

namespace WebVella.Erp.Service.Reporting.Database.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebVella.Erp.Service.Reporting.Database.TimelogProjection", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("TaskId")
                    .IsRequired()
                    .HasColumnType("uuid")
                    .HasColumnName("task_id");

                b.Property<Guid?>("ProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("project_id");

                b.Property<Guid?>("AccountId")
                    .HasColumnType("uuid")
                    .HasColumnName("account_id");

                b.Property<bool>("IsBillable")
                    .IsRequired()
                    .HasColumnType("boolean")
                    .HasColumnName("is_billable");

                b.Property<decimal>("Minutes")
                    .IsRequired()
                    .HasDefaultValue(0m)
                    .HasColumnType("numeric")
                    .HasColumnName("minutes");

                b.Property<DateTime>("LoggedOn")
                    .IsRequired()
                    .HasColumnType("timestamptz")
                    .HasColumnName("logged_on");

                b.Property<string>("Scope")
                    .IsRequired()
                    .HasDefaultValue("projects")
                    .HasColumnType("text")
                    .HasColumnName("scope");

                b.Property<DateTime>("CreatedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_on");

                b.Property<DateTime>("LastModifiedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("last_modified_on");

                b.HasKey("Id");

                b.HasIndex("TaskId")
                    .HasDatabaseName("idx_timelog_proj_task_id");

                b.HasIndex("ProjectId")
                    .HasDatabaseName("idx_timelog_proj_project_id");

                b.HasIndex("AccountId")
                    .HasDatabaseName("idx_timelog_proj_account_id");

                b.HasIndex("LoggedOn")
                    .HasDatabaseName("idx_timelog_proj_logged_on");

                b.HasIndex("Scope")
                    .HasDatabaseName("idx_timelog_proj_scope");

                b.HasIndex("LoggedOn", "Scope")
                    .HasDatabaseName("idx_timelog_proj_logged_on_scope");

                b.ToTable("timelog_projections");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Reporting.Database.TaskProjection", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasDefaultValue("")
                    .HasColumnType("text")
                    .HasColumnName("subject");

                b.Property<string>("TaskTypeLabel")
                    .HasColumnType("text")
                    .HasColumnName("task_type_label");

                b.Property<DateTime>("CreatedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_on");

                b.Property<DateTime>("LastModifiedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("last_modified_on");

                b.HasKey("Id");

                b.HasIndex("Subject")
                    .HasDatabaseName("idx_task_proj_subject");

                b.ToTable("task_projections");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Reporting.Database.ProjectProjection", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasDefaultValue("")
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<Guid?>("AccountId")
                    .HasColumnType("uuid")
                    .HasColumnName("account_id");

                b.Property<DateTime>("CreatedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_on");

                b.Property<DateTime>("LastModifiedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("last_modified_on");

                b.HasKey("Id");

                b.HasIndex("AccountId")
                    .HasDatabaseName("idx_project_proj_account_id");

                b.HasIndex("Name")
                    .HasDatabaseName("idx_project_proj_name");

                b.ToTable("project_projections");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Reporting.Database.ReportDefinition", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("ReportType")
                    .IsRequired()
                    .HasDefaultValue("timelog")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("report_type");

                b.Property<string>("ParametersJson")
                    .IsRequired()
                    .HasDefaultValue("{}")
                    .HasColumnType("text")
                    .HasColumnName("parameters_json");

                b.Property<Guid>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<DateTime>("CreatedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("created_on");

                b.Property<DateTime>("LastModifiedOn")
                    .IsRequired()
                    .HasDefaultValueSql("now()")
                    .HasColumnType("timestamptz")
                    .HasColumnName("last_modified_on");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .HasDatabaseName("idx_report_def_name");

                b.HasIndex("ReportType")
                    .HasDatabaseName("idx_report_def_report_type");

                b.HasIndex("CreatedBy")
                    .HasDatabaseName("idx_report_def_created_by");

                b.ToTable("report_definitions");
            });
#pragma warning restore 612, 618
        }
    }
}
