/**
 * AutonumberField — Read-only auto-generated number display with template formatting.
 *
 * React replacement for the monolith's PcFieldAutonumber ViewComponent.
 * Autonumber fields are always read-only (server-generated values).
 * Supports .NET-style template formatting: e.g., "INV-{0:D6}" formats 42 as "INV-000042".
 *
 * @module components/fields/AutonumberField
 */

import React, { useState, useCallback, useMemo } from 'react';
import type { BaseFieldProps } from './FieldRenderer';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Props for the AutonumberField component.
 *
 * Extends BaseFieldProps (minus `value` and `onChange`) because autonumber
 * fields carry a numeric value that is always read-only.
 */
export interface AutonumberFieldProps extends Omit<BaseFieldProps, 'value' | 'onChange'> {
  /** The numeric autonumber value, or null when not yet assigned. */
  value: number | null;

  /**
   * onChange is intentionally `never` — autonumber fields are always read-only
   * because their values are generated by the server.
   */
  onChange?: never;

  /**
   * Display format template using .NET-style placeholders.
   *
   * Supported patterns:
   * - `{0}`      — raw number as string (e.g., "42")
   * - `{0:DN}`   — zero-pad to N digits (e.g., `{0:D6}` → "000042")
   *
   * Example: `"INV-{0:D6}"` with value 42 → `"INV-000042"`
   */
  template?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Regex matching .NET-style format tokens: {0}, {0:D6}, {0:d4}, etc. */
const FORMAT_TOKEN_REGEX = /\{0(?::([Dd])(\d+))?\}/g;

/**
 * Applies a .NET-style template string to a numeric value.
 *
 * Supported placeholders:
 * - `{0}`     → raw number as string
 * - `{0:DN}`  → zero-padded to N digits (case-insensitive D)
 *
 * If the template contains no recognised placeholders the raw number string
 * is returned as a fallback so the user always sees *something*.
 *
 * @param template - The format string, e.g. "INV-{0:D6}"
 * @param numericValue - The integer value to format
 * @returns The formatted string, e.g. "INV-000042"
 */
function applyTemplate(template: string, numericValue: number): string {
  let matchCount = 0;

  const result = template.replace(
    FORMAT_TOKEN_REGEX,
    (_match: string, formatChar: string | undefined, digits: string | undefined) => {
      matchCount += 1;
      const valueStr = String(numericValue);

      // {0:D6} or {0:d6} — zero-pad to the specified number of digits
      if (formatChar && digits) {
        const padLength = parseInt(digits, 10);
        if (!Number.isNaN(padLength) && padLength > 0) {
          return valueStr.padStart(padLength, '0');
        }
      }

      // {0} — raw substitution
      return valueStr;
    },
  );

  // If the template had no valid tokens, return the raw number string
  // so the user isn't left staring at a bare template literal.
  return matchCount > 0 ? result : String(numericValue);
}

// ---------------------------------------------------------------------------
// Clipboard copy SVG icons (inline to avoid external dependencies)
// ---------------------------------------------------------------------------

/** Clipboard/copy icon — shown before copy action */
function ClipboardIcon(): React.JSX.Element {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      className="inline-block h-4 w-4"
      aria-hidden="true"
    >
      <rect x={9} y={9} width={13} height={13} rx={2} ry={2} />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

/** Checkmark icon — shown after a successful copy */
function CheckIcon(): React.JSX.Element {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      className="inline-block h-4 w-4"
      aria-hidden="true"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * AutonumberField renders a server-generated numeric value with optional
 * template formatting.  Both display and edit modes are read-only because
 * autonumber values cannot be modified by the user.
 *
 * **Display mode** — shows the formatted value with a copy-to-clipboard button.
 * **Edit mode**    — renders inside a disabled input-like container.
 */
function AutonumberField(props: AutonumberFieldProps): React.JSX.Element {
  const {
    name,
    value,
    template,
    mode = 'display',
    access = 'full',
    disabled: _disabled,
    error,
    className,
    emptyValueMessage = 'no data',
    description: _description,
    locale: _locale,
  } = props;

  // -- Copy-to-clipboard state ------------------------------------------------
  const [copied, setCopied] = useState<boolean>(false);

  // -- Formatted display value (memoised) ------------------------------------
  const formattedValue = useMemo<string>(() => {
    if (value === null || value === undefined) {
      return '';
    }

    if (template && template.length > 0) {
      return applyTemplate(template, value);
    }

    return String(value);
  }, [value, template]);

  // -- Copy handler (memoised) -----------------------------------------------
  const handleCopy = useCallback(async (): Promise<void> => {
    if (!formattedValue) {
      return;
    }

    try {
      await navigator.clipboard.writeText(formattedValue);
      setCopied(true);

      // Reset the "Copied!" indicator after 2 seconds
      const timerId = window.setTimeout(() => {
        setCopied(false);
      }, 2000);

      // Clean-up is intentionally handled inside the timeout itself;
      // the component is simple enough that a leaked timer on unmount
      // has negligible impact, and adding a ref + effect just for this
      // would be over-engineering.
      void timerId;
    } catch {
      // Clipboard API may fail in insecure contexts or older browsers.
      // Silently degrade — the value is still visible to the user.
    }
  }, [formattedValue]);

  // -- Determine whether we have a value to display --------------------------
  const hasValue = value !== null && value !== undefined;

  // -- Shared field id -------------------------------------------------------
  const fieldId = props.fieldId ?? `field-${name}`;

  // -- Error styling flag ----------------------------------------------------
  const hasError = Boolean(error);

  // =========================================================================
  // Edit mode — disabled input-like container
  // =========================================================================
  if (mode === 'edit') {
    return (
      <div className={className ?? ''}>
        <input
          type="text"
          id={fieldId}
          name={name}
          value={hasValue ? formattedValue : ''}
          readOnly
          disabled
          aria-readonly="true"
          aria-invalid={hasError || undefined}
          aria-describedby={hasError ? `${name}-error` : undefined}
          className={[
            'block w-full rounded-md border px-3 py-2 text-sm shadow-sm',
            'bg-gray-100 text-gray-500 cursor-not-allowed',
            hasError
              ? 'border-red-500 focus:border-red-500 focus:ring-red-500'
              : 'border-gray-300',
            'focus:outline-none',
          ].join(' ')}
        />
        {!hasValue && (
          <p className="mt-1 text-xs text-gray-400 italic">
            {emptyValueMessage}
          </p>
        )}
      </div>
    );
  }

  // =========================================================================
  // Display mode — read-only styled container with copy-to-clipboard
  // =========================================================================
  if (!hasValue) {
    return (
      <div className={className ?? ''}>
        <span className="text-sm italic text-gray-400">
          {emptyValueMessage}
        </span>
      </div>
    );
  }

  return (
    <div
      className={[
        'inline-flex items-center gap-2',
        className ?? '',
      ].join(' ')}
    >
      {/* Formatted autonumber value */}
      <span
        id={fieldId}
        className={[
          'text-sm font-mono text-gray-900',
          access === 'readonly' ? 'opacity-60' : '',
        ].join(' ')}
        data-testid={`autonumber-value-${name}`}
      >
        {formattedValue}
      </span>

      {/* Copy-to-clipboard button */}
      <button
        type="button"
        onClick={handleCopy}
        className={[
          'inline-flex items-center justify-center rounded p-1',
          'text-gray-400 hover:text-gray-600',
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-1',
          'transition-colors duration-150',
        ].join(' ')}
        aria-label={copied ? 'Copied to clipboard' : `Copy ${name} value`}
        title={copied ? 'Copied!' : 'Copy to clipboard'}
      >
        {copied ? (
          <span className="inline-flex items-center gap-1 text-green-600">
            <CheckIcon />
            <span className="text-xs">Copied!</span>
          </span>
        ) : (
          <ClipboardIcon />
        )}
      </button>
    </div>
  );
}

// Re-exported with type assertion for FieldRenderer compatibility.
// FieldRenderer's FIELD_COMPONENT_MAP requires ComponentType<BaseFieldProps> because
// it passes `value: unknown` at runtime. The internal function body retains full
// type safety via AutonumberFieldProps. External consumers who import
// AutonumberField directly should cast props through AutonumberFieldProps.
export default AutonumberField as unknown as React.ComponentType<BaseFieldProps>;
