// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebVella.Erp.Service.Project.Database;

namespace WebVella.Erp.Service.Project.Database.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.CommentAttachmentRelation", b =>
            {
                b.Property<Guid>("OriginId")
                    .HasColumnType("uuid")
                    .HasColumnName("origin_id");

                b.Property<Guid>("TargetId")
                    .HasColumnType("uuid")
                    .HasColumnName("target_id");

                b.HasKey("OriginId", "TargetId");

                b.ToTable("rel_comment_nn_attachment");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.CommentEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Body")
                    .HasColumnType("text")
                    .HasColumnName("body");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_on");

                b.Property<string>("LRelatedRecords")
                    .HasColumnType("text")
                    .HasColumnName("l_related_records");

                b.Property<string>("LScope")
                    .HasColumnType("text")
                    .HasColumnName("l_scope");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_id");

                b.HasKey("Id");

                b.ToTable("rec_comment");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.FeedItemEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Body")
                    .HasColumnType("text")
                    .HasColumnName("body");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_on");

                b.Property<string>("LRelatedRecords")
                    .HasColumnType("text")
                    .HasColumnName("l_related_records");

                b.Property<string>("LScope")
                    .HasColumnType("text")
                    .HasColumnName("l_scope");

                b.Property<string>("Subject")
                    .HasColumnType("text")
                    .HasColumnName("subject");

                b.Property<string>("Type")
                    .HasColumnType("text")
                    .HasColumnName("type");

                b.HasKey("Id");

                b.ToTable("rec_feed_item");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.MilestoneEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_date");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_date");

                b.Property<string>("Status")
                    .HasColumnType("text")
                    .HasColumnName("status");

                b.HasKey("Id");

                b.ToTable("rec_milestone");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.MilestoneTaskRelation", b =>
            {
                b.Property<Guid>("OriginId")
                    .HasColumnType("uuid")
                    .HasColumnName("origin_id");

                b.Property<Guid>("TargetId")
                    .HasColumnType("uuid")
                    .HasColumnName("target_id");

                b.HasKey("OriginId", "TargetId");

                b.HasIndex("TargetId");

                b.ToTable("rel_milestone_nn_task");

                b.HasOne("WebVella.Erp.Service.Project.Database.MilestoneEntity", "Milestone")
                    .WithMany()
                    .HasForeignKey("OriginId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("WebVella.Erp.Service.Project.Database.TaskEntity", "Task")
                    .WithMany("MilestoneTaskRelations")
                    .HasForeignKey("TargetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Milestone");

                b.Navigation("Task");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.ProjectEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Abbr")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("abbr");

                b.Property<string>("Color")
                    .HasColumnType("text")
                    .HasColumnName("color");

                b.Property<string>("Description")
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_date");

                b.Property<string>("Icon")
                    .HasColumnType("text")
                    .HasColumnName("icon");

                b.Property<bool>("IsBillable")
                    .HasColumnType("boolean")
                    .HasColumnName("is_billable");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<Guid?>("OwnerId")
                    .HasColumnType("uuid")
                    .HasColumnName("owner_id");

                b.Property<string>("ScopeKey")
                    .HasColumnType("text")
                    .HasColumnName("scope_key");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_date");

                b.Property<decimal>("XBillableHours")
                    .HasPrecision(18, 3)
                    .HasColumnName("x_billable_hours");

                b.Property<decimal>("XBudget")
                    .HasPrecision(18, 3)
                    .HasColumnName("x_budget");

                b.Property<int>("XMilestonesMissed")
                    .HasColumnType("integer")
                    .HasColumnName("x_milestones_missed");

                b.Property<int>("XMilestonesOnTrack")
                    .HasColumnType("integer")
                    .HasColumnName("x_milestones_on_track");

                b.Property<decimal>("XNonbillableHours")
                    .HasPrecision(18, 3)
                    .HasColumnName("x_nonbillable_hours");

                b.Property<int>("XOverdueTasks")
                    .HasColumnType("integer")
                    .HasColumnName("x_overdue_tasks");

                b.Property<int>("XTasksCompleted")
                    .HasColumnType("integer")
                    .HasColumnName("x_tasks_completed");

                b.Property<int>("XTasksInProgress")
                    .HasColumnType("integer")
                    .HasColumnName("x_tasks_in_progress");

                b.Property<int>("XTasksNotStarted")
                    .HasColumnType("integer")
                    .HasColumnName("x_tasks_not_started");

                b.HasKey("Id");

                b.ToTable("rec_project");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.ProjectMilestoneRelation", b =>
            {
                b.Property<Guid>("OriginId")
                    .HasColumnType("uuid")
                    .HasColumnName("origin_id");

                b.Property<Guid>("TargetId")
                    .HasColumnType("uuid")
                    .HasColumnName("target_id");

                b.HasKey("OriginId", "TargetId");

                b.HasIndex("TargetId");

                b.ToTable("rel_project_nn_milestone");

                b.HasOne("WebVella.Erp.Service.Project.Database.ProjectEntity", "Project")
                    .WithMany()
                    .HasForeignKey("OriginId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("WebVella.Erp.Service.Project.Database.MilestoneEntity", "Milestone")
                    .WithMany()
                    .HasForeignKey("TargetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Milestone");

                b.Navigation("Project");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.ProjectTaskRelation", b =>
            {
                b.Property<Guid>("OriginId")
                    .HasColumnType("uuid")
                    .HasColumnName("origin_id");

                b.Property<Guid>("TargetId")
                    .HasColumnType("uuid")
                    .HasColumnName("target_id");

                b.HasKey("OriginId", "TargetId");

                b.HasIndex("TargetId");

                b.ToTable("rel_project_nn_task");

                b.HasOne("WebVella.Erp.Service.Project.Database.ProjectEntity", "Project")
                    .WithMany()
                    .HasForeignKey("OriginId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("WebVella.Erp.Service.Project.Database.TaskEntity", "Task")
                    .WithMany("ProjectTaskRelations")
                    .HasForeignKey("TargetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");

                b.Navigation("Task");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.TaskEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Body")
                    .HasColumnType("text")
                    .HasColumnName("body");

                b.Property<DateTime?>("CompletedOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("completed_on");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_on");

                b.Property<string>("Key")
                    .HasColumnType("text")
                    .HasColumnName("key");

                b.Property<string>("LRelatedRecords")
                    .HasColumnType("text")
                    .HasColumnName("l_related_records");

                b.Property<string>("LScope")
                    .HasColumnType("text")
                    .HasColumnName("l_scope");

                b.Property<long>("Number")
                    .HasColumnType("bigint")
                    .HasColumnName("number");

                b.Property<Guid?>("OwnerId")
                    .HasColumnType("uuid")
                    .HasColumnName("owner_id");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_id");

                b.Property<string>("Priority")
                    .HasColumnType("text")
                    .HasColumnName("priority");

                b.Property<Guid?>("RecurrenceId")
                    .HasColumnType("uuid")
                    .HasColumnName("recurrence_id");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_date");

                b.Property<Guid?>("StatusId")
                    .HasColumnType("uuid")
                    .HasColumnName("status_id");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("subject");

                b.Property<DateTime?>("TargetDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("target_date");

                b.Property<Guid?>("TypeId")
                    .HasColumnType("uuid")
                    .HasColumnName("type_id");

                b.Property<decimal>("XBillableHours")
                    .HasPrecision(18, 3)
                    .HasColumnName("x_billable_minutes");

                b.Property<decimal>("XNonbillableHours")
                    .HasPrecision(18, 3)
                    .HasColumnName("x_nonbillable_minutes");

                b.Property<string>("XSearch")
                    .HasColumnType("text")
                    .HasColumnName("x_search");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.HasIndex("StatusId");

                b.HasIndex("TypeId");

                b.ToTable("rec_task");

                b.HasOne("WebVella.Erp.Service.Project.Database.TaskEntity", "Parent")
                    .WithMany("Children")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("WebVella.Erp.Service.Project.Database.TaskStatusEntity", "Status")
                    .WithMany()
                    .HasForeignKey("StatusId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("WebVella.Erp.Service.Project.Database.TaskTypeEntity", "Type")
                    .WithMany()
                    .HasForeignKey("TypeId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Children");

                b.Navigation("MilestoneTaskRelations");

                b.Navigation("Parent");

                b.Navigation("ProjectTaskRelations");

                b.Navigation("Status");

                b.Navigation("Type");
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.TaskStatusEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Color")
                    .HasColumnType("text")
                    .HasColumnName("color");

                b.Property<string>("IconClass")
                    .HasColumnType("text")
                    .HasColumnName("icon_class");

                b.Property<bool>("IsClosed")
                    .HasColumnType("boolean")
                    .HasColumnName("is_closed");

                b.Property<bool>("IsDefault")
                    .HasColumnType("boolean")
                    .HasColumnName("is_default");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("is_enabled");

                b.Property<string>("LScope")
                    .HasColumnType("text")
                    .HasColumnName("l_scope");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("label");

                b.Property<int>("SortOrder")
                    .HasColumnType("integer")
                    .HasColumnName("sort_index");

                b.HasKey("Id");

                b.ToTable("rec_task_status");

                b.HasData(
                    new
                    {
                        Id = new Guid("f3fdd750-0c16-4215-93b3-5373bd528d1f"),
                        IsClosed = false,
                        IsDefault = true,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Not Started",
                        SortOrder = 1
                    },
                    new
                    {
                        Id = new Guid("20d73f63-3501-4565-a55e-2d291549a9bd"),
                        IsClosed = false,
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "In Progress",
                        SortOrder = 2
                    },
                    new
                    {
                        Id = new Guid("8b2aa2af-17dd-400a-a221-78ee744c4866"),
                        Color = "",
                        IconClass = "",
                        IsClosed = false,
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Blocked",
                        SortOrder = 3
                    },
                    new
                    {
                        Id = new Guid("b1cc69e5-ce09-40e0-8785-b6452b257bdf"),
                        Color = "",
                        IconClass = "",
                        IsClosed = true,
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Completed",
                        SortOrder = 4
                    },
                    new
                    {
                        Id = new Guid("a1e527fd-4472-4b39-a1d4-af4905d2310c"),
                        Color = "",
                        IconClass = "",
                        IsClosed = true,
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Rejected",
                        SortOrder = 5
                    });
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.TaskTypeEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Color")
                    .HasColumnType("text")
                    .HasColumnName("color");

                b.Property<string>("IconClass")
                    .HasColumnType("text")
                    .HasColumnName("icon_class");

                b.Property<bool>("IsDefault")
                    .HasColumnType("boolean")
                    .HasColumnName("is_default");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("is_enabled");

                b.Property<string>("LScope")
                    .HasColumnType("text")
                    .HasColumnName("l_scope");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("label");

                b.Property<int>("SortOrder")
                    .HasColumnType("integer")
                    .HasColumnName("sort_index");

                b.HasKey("Id");

                b.ToTable("rec_task_type");

                b.HasData(
                    new
                    {
                        Id = new Guid("da9bf72d-3655-4c51-9f99-047ef9297bf2"),
                        IsDefault = true,
                        IsEnabled = true,
                        LScope = "",
                        Label = "General",
                        SortOrder = 1
                    },
                    new
                    {
                        Id = new Guid("7b191135-5fbb-4db9-bf24-1a5fc72d8cd5"),
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Call",
                        SortOrder = 2
                    },
                    new
                    {
                        Id = new Guid("489b16e1-91b1-4a05-b247-50ed74f7aaaf"),
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Email",
                        SortOrder = 3
                    },
                    new
                    {
                        Id = new Guid("894ba1ef-1b31-440c-9b33-f301d047d8fb"),
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Meeting",
                        SortOrder = 4
                    },
                    new
                    {
                        Id = new Guid("ddb9c170-706d-4b17-a8ee-78ed3a544fa3"),
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "",
                        Label = "Send Quote",
                        SortOrder = 5
                    },
                    new
                    {
                        Id = new Guid("6105dcf4-4115-435f-94bb-0190d45d1b87"),
                        Color = "#9C27B0",
                        IconClass = "far fa-fw fa-caret-square-up",
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "[\"projects\"]",
                        Label = "Improvement",
                        SortOrder = 2
                    },
                    new
                    {
                        Id = new Guid("a0465e9f-5d5f-433d-acf1-1da0eaec78b4"),
                        Color = "#4CAF50",
                        IconClass = "fas fa-fw fa-plus-square",
                        IsDefault = true,
                        IsEnabled = true,
                        LScope = "[\"projects\"]",
                        Label = "New Feature",
                        SortOrder = 1
                    },
                    new
                    {
                        Id = new Guid("c0a2554c-f59a-434e-be00-217a416f8efd"),
                        Color = "#F44336",
                        IconClass = "fas fa-fw fa-bug",
                        IsDefault = false,
                        IsEnabled = true,
                        LScope = "[\"projects\"]",
                        Label = "Bug",
                        SortOrder = 3
                    });
            });

            modelBuilder.Entity("WebVella.Erp.Service.Project.Database.TimelogEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Body")
                    .HasColumnType("text")
                    .HasColumnName("body");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_on");

                b.Property<bool>("IsBillable")
                    .HasColumnType("boolean")
                    .HasColumnName("is_billable");

                b.Property<string>("LRelatedRecords")
                    .HasColumnType("text")
                    .HasColumnName("l_related_records");

                b.Property<string>("LScope")
                    .HasColumnType("text")
                    .HasColumnName("l_scope");

                b.Property<decimal>("Minutes")
                    .HasPrecision(18, 3)
                    .HasColumnName("minutes");

                b.HasKey("Id");

                b.ToTable("rec_timelog");
            });
#pragma warning restore 612, 618
        }
    }
}
