// =========================================================================
// WebVella ERP — Gateway Integration Test Infrastructure
// =========================================================================
// Custom WebApplicationFactory<Program> subclass providing shared test
// infrastructure for all Gateway integration tests. Configures:
//   - In-memory configuration with JWT settings matching monolith exactly
//     (Config.json lines 24-28: Key, Issuer, Audience)
//   - Mock HTTP handlers for all six backend service named HttpClients
//     (Core, CRM, Project, Mail, Reporting, Admin)
//   - JWT token generation utilities matching AuthService.cs claim structure
//     (lines 145-160: NameIdentifier, Email, Role, token_refresh_after)
//   - Authenticated and anonymous HttpClient factories with AllowAutoRedirect=false
//
// JWT settings are EXACT copies from monolith Config.json to ensure tokens
// generated by tests are validated by the same pipeline configuration used
// in production (Startup.cs lines 88-125 JWT Bearer setup).
// =========================================================================

using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using Moq;
using Moq.Protected;
using Newtonsoft.Json;

namespace WebVella.Erp.Tests.Gateway.Integration
{
    /// <summary>
    /// Shared <see cref="WebApplicationFactory{TEntryPoint}"/> subclass that provides
    /// test infrastructure for all Gateway integration tests. Configures the test host
    /// with mock services, test JWT settings matching the monolith EXACTLY, and mock
    /// HTTP handlers to intercept forwarded requests to backend microservices.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>Program</c> refers to the Gateway's entry point class generated by the
    /// top-level statements in <c>src/Gateway/WebVella.Erp.Gateway/Program.cs</c>.
    /// The Gateway project must declare <c>[assembly: InternalsVisibleTo("WebVella.Erp.Tests.Gateway")]</c>
    /// or expose <c>Program</c> as <c>public partial class Program { }</c> for this reference to resolve.
    /// </para>
    /// <para>
    /// JWT constants are sourced from the monolith's <c>Config.json</c> (lines 24-28)
    /// and the claim structure from <c>AuthService.cs</c> (lines 145-160).
    /// </para>
    /// </remarks>
    public class CustomWebApplicationFactory : WebApplicationFactory<Program>
    {
        // =====================================================================
        // JWT Constants — EXACT copies from monolith Config.json (lines 24-28)
        // These values MUST match the Gateway's JWT validation configuration
        // (Startup.cs lines 102-114) for tokens to be accepted by the pipeline.
        // =====================================================================

        /// <summary>
        /// JWT signing key matching monolith Config.json line 25 EXACTLY.
        /// Used for HMAC-SHA256 symmetric signing of test JWT tokens.
        /// </summary>
        public const string TestJwtKey = "ThisIsMySecretKeyThisIsMySecretKeyThisIsMySecretKey";

        /// <summary>
        /// JWT issuer matching monolith Config.json line 26 EXACTLY.
        /// Validated by JWT Bearer middleware via <c>ValidateIssuer = true</c>.
        /// </summary>
        public const string TestJwtIssuer = "webvella-erp";

        /// <summary>
        /// JWT audience matching monolith Config.json line 27 EXACTLY.
        /// Validated by JWT Bearer middleware via <c>ValidateAudience = true</c>.
        /// </summary>
        public const string TestJwtAudience = "webvella-erp";

        /// <summary>
        /// JWT token expiry duration in minutes — from AuthService.cs line 19:
        /// <c>private const double JWT_TOKEN_EXPIRY_DURATION_MINUTES = 1440;</c>
        /// This is 24 hours.
        /// </summary>
        private const double JwtTokenExpiryMinutes = 1440;

        /// <summary>
        /// JWT token refresh interval in minutes — from AuthService.cs line 20:
        /// <c>private const double JWT_TOKEN_FORCE_REFRESH_MINUTES = 120;</c>
        /// This is 2 hours.
        /// </summary>
        private const double JwtTokenRefreshMinutes = 120;

        // =====================================================================
        // Mock Backend Handler — intercepts all HTTP requests forwarded by the
        // Gateway's RequestRoutingMiddleware to backend microservices.
        // =====================================================================

        private readonly Mock<HttpMessageHandler> _mockBackendHandler;

        /// <summary>
        /// Exposes the mock backend HTTP message handler for individual tests to
        /// configure specific return values for backend service calls. Tests can
        /// use <c>MockBackendHandler.Protected().Setup(...)</c> to override the
        /// default success response with custom responses for specific scenarios.
        /// </summary>
        public Mock<HttpMessageHandler> MockBackendHandler => _mockBackendHandler;

        /// <summary>
        /// Initializes a new instance of <see cref="CustomWebApplicationFactory"/>
        /// with the default mock backend handler configured to return a successful
        /// <c>BaseResponseModel</c>-shaped JSON response for all forwarded requests.
        /// </summary>
        /// <remarks>
        /// The default mock response matches the exact shape of the monolith's
        /// <c>BaseResponseModel</c> (BaseModels.cs lines 8-38) with Newtonsoft.Json
        /// camelCase property names from <c>[JsonProperty]</c> annotations:
        /// <list type="bullet">
        ///   <item><c>success</c> (bool) — line 13</item>
        ///   <item><c>timestamp</c> (DateTime) — line 10</item>
        ///   <item><c>errors</c> (array) — line 22</item>
        ///   <item><c>message</c> (string|null) — line 16</item>
        ///   <item><c>object</c> (any|null) — ResponseModel line 42</item>
        ///   <item><c>hash</c> (string|null) — line 19</item>
        ///   <item><c>accessWarnings</c> (array) — line 25</item>
        /// </list>
        /// Note: <c>statusCode</c> is marked <c>[JsonIgnore]</c> (line 28) and is NOT serialized.
        /// </remarks>
        public CustomWebApplicationFactory()
        {
            _mockBackendHandler = new Mock<HttpMessageHandler>();

            // Configure default mock response matching BaseResponseModel envelope shape
            // from BaseModels.cs. Uses Newtonsoft.Json (NOT System.Text.Json) to match
            // the monolith's serialization behavior with [JsonProperty] camelCase naming.
            _mockBackendHandler
                .Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.OK,
                    Content = new StringContent(
                        JsonConvert.SerializeObject(new
                        {
                            // BaseResponseModel properties (BaseModels.cs lines 10-26)
                            success = true,
                            timestamp = DateTime.UtcNow,
                            errors = new object[0],
                            message = (string)null,
                            // ResponseModel property (BaseModels.cs line 42)
                            @object = (object)null,
                            // BaseResponseModel additional properties
                            hash = (string)null,
                            accessWarnings = new object[0]
                        }),
                        Encoding.UTF8,
                        "application/json")
                });
        }

        /// <summary>
        /// Configures the test web host with:
        /// <list type="number">
        ///   <item>"Development" environment for dev-mode error details</item>
        ///   <item>In-memory configuration overrides for JWT settings and service routes</item>
        ///   <item>Mock HTTP message handlers for all six backend service named HttpClients</item>
        /// </list>
        /// </summary>
        /// <param name="builder">The web host builder to configure.</param>
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            // Set environment to Development for testing — enables
            // UseDeveloperExceptionPage (Gateway Program.cs line 339)
            builder.UseEnvironment("Development");

            // Override configuration with test-specific values, replacing real
            // backend service URLs with localhost test ports and injecting
            // JWT settings matching monolith Config.json lines 24-28.
            builder.ConfigureAppConfiguration((context, config) =>
            {
                config.AddInMemoryCollection(new Dictionary<string, string>
                {
                    // JWT settings — EXACT match to monolith Config.json
                    ["Settings:Jwt:Key"] = TestJwtKey,
                    ["Settings:Jwt:Issuer"] = TestJwtIssuer,
                    ["Settings:Jwt:Audience"] = TestJwtAudience,

                    // General settings — from Config.json lines 2-13
                    ["Settings:DevelopmentMode"] = "true",
                    ["Settings:Locale"] = "en-US",
                    ["Settings:Lang"] = "en",
                    ["Settings:EncryptionKey"] = "BC93B776A42877CFEE808823BA8B37C83B6B0AD23198AC3AF2B5A54DCB647658",

                    // Backend service route URLs — unique localhost ports
                    // to avoid conflicts, consumed by RouteConfiguration and
                    // the IHttpClientFactory named client registrations in
                    // Gateway Program.cs lines 243-290.
                    ["ServiceRoutes:CoreServiceUrl"] = "http://localhost:9001",
                    ["ServiceRoutes:CrmServiceUrl"] = "http://localhost:9002",
                    ["ServiceRoutes:ProjectServiceUrl"] = "http://localhost:9003",
                    ["ServiceRoutes:MailServiceUrl"] = "http://localhost:9004",
                    ["ServiceRoutes:ReportingServiceUrl"] = "http://localhost:9005",
                    ["ServiceRoutes:AdminServiceUrl"] = "http://localhost:9006",
                });
            });

            // Replace real IHttpClientFactory named client registrations with
            // mock handlers. Each named client (registered in Gateway Program.cs
            // lines 243-290) gets the shared _mockBackendHandler so all forwarded
            // HTTP requests are intercepted and return the default BaseResponseModel
            // success envelope (or whatever response is configured by individual tests).
            builder.ConfigureTestServices(services =>
            {
                // Core Platform service — entities, records, security, files, search
                services.AddHttpClient("CoreService")
                    .ConfigurePrimaryHttpMessageHandler(() => _mockBackendHandler.Object);

                // CRM service — accounts, contacts, cases, addresses, search
                services.AddHttpClient("CrmService")
                    .ConfigurePrimaryHttpMessageHandler(() => _mockBackendHandler.Object);

                // Project/Task service — projects, tasks, timelogs, comments, feed
                services.AddHttpClient("ProjectService")
                    .ConfigurePrimaryHttpMessageHandler(() => _mockBackendHandler.Object);

                // Mail/Notification service — email send, queue, SMTP config
                services.AddHttpClient("MailService")
                    .ConfigurePrimaryHttpMessageHandler(() => _mockBackendHandler.Object);

                // Reporting service — timelog reports, task summaries
                services.AddHttpClient("ReportingService")
                    .ConfigurePrimaryHttpMessageHandler(() => _mockBackendHandler.Object);

                // Admin/SDK service — code gen, logs, datasources, sitemap
                services.AddHttpClient("AdminService")
                    .ConfigurePrimaryHttpMessageHandler(() => _mockBackendHandler.Object);
            });
        }

        // =====================================================================
        // HttpClient Factory Methods
        // =====================================================================

        /// <summary>
        /// Creates an <see cref="HttpClient"/> with a valid JWT Bearer token in the
        /// Authorization header, configured with <c>AllowAutoRedirect = false</c>
        /// so tests can inspect raw redirect responses (e.g., 302 to /login).
        /// </summary>
        /// <param name="userId">
        /// User ID for the <see cref="ClaimTypes.NameIdentifier"/> claim.
        /// Matches AuthService.cs line 148: <c>new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())</c>
        /// </param>
        /// <param name="email">
        /// Email address for the <see cref="ClaimTypes.Email"/> claim.
        /// Matches AuthService.cs line 149: <c>new Claim(ClaimTypes.Email, user.Email)</c>
        /// </param>
        /// <param name="roles">
        /// Role names for <c>ClaimTypes.Role.ToString()</c> claims.
        /// Matches AuthService.cs line 150: <c>new Claim(ClaimTypes.Role.ToString(), role.Name)</c>
        /// </param>
        /// <returns>An authenticated <see cref="HttpClient"/> with JWT Bearer token.</returns>
        public HttpClient CreateAuthenticatedClient(Guid userId, string email, string[] roles)
        {
            var client = CreateClient(new WebApplicationFactoryClientOptions
            {
                AllowAutoRedirect = false
            });

            var token = GenerateJwtToken(userId, email, roles);
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", token);

            return client;
        }

        /// <summary>
        /// Creates an <see cref="HttpClient"/> with no authentication credentials,
        /// configured with <c>AllowAutoRedirect = false</c> so tests can inspect
        /// raw 302 redirect responses to /login (Startup.cs line 97).
        /// </summary>
        /// <returns>An anonymous <see cref="HttpClient"/> without credentials.</returns>
        public HttpClient CreateAnonymousClient()
        {
            return CreateClient(new WebApplicationFactoryClientOptions
            {
                AllowAutoRedirect = false
            });
        }

        // =====================================================================
        // JWT Token Generation — matches AuthService.cs BuildTokenAsync exactly
        // (lines 145-160)
        // =====================================================================

        /// <summary>
        /// Generates a valid JWT token with claims matching the monolith's
        /// <c>AuthService.BuildTokenAsync</c> method (lines 145-160) EXACTLY:
        /// <list type="bullet">
        ///   <item><c>ClaimTypes.NameIdentifier</c> — user ID (line 148)</item>
        ///   <item><c>ClaimTypes.Email</c> — email address (line 149)</item>
        ///   <item><c>ClaimTypes.Role.ToString()</c> — one per role (line 150)</item>
        ///   <item><c>"token_refresh_after"</c> — binary DateTime (lines 152-153)</item>
        /// </list>
        /// Algorithm: <c>SecurityAlgorithms.HmacSha256Signature</c> (line 156).
        /// Expiry: 1440 minutes / 24 hours (line 19).
        /// </summary>
        /// <param name="userId">User ID for the NameIdentifier claim.</param>
        /// <param name="email">Email address for the Email claim.</param>
        /// <param name="roles">Role names for Role claims.</param>
        /// <returns>A JWT token string in compact serialization format.</returns>
        public string GenerateJwtToken(Guid userId, string email, string[] roles)
        {
            var claims = new List<Claim>
            {
                // AuthService.cs line 148
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                // AuthService.cs line 149
                new Claim(ClaimTypes.Email, email)
            };

            // AuthService.cs line 150: uses ClaimTypes.Role.ToString() as the claim type
            // (NOT ClaimTypes.Role directly — the .ToString() call is in the monolith)
            foreach (var role in roles)
            {
                claims.Add(new Claim(ClaimTypes.Role.ToString(), role));
            }

            // AuthService.cs lines 152-153: token_refresh_after with binary DateTime
            DateTime tokenRefreshAfterDateTime = DateTime.UtcNow.AddMinutes(JwtTokenRefreshMinutes);
            claims.Add(new Claim("token_refresh_after", tokenRefreshAfterDateTime.ToBinary().ToString()));

            // AuthService.cs lines 155-156: HMAC-SHA256 signing
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(TestJwtKey));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256Signature);

            // AuthService.cs lines 157-158: token descriptor with issuer, audience, claims, expiry
            var tokenDescriptor = new JwtSecurityToken(
                issuer: TestJwtIssuer,
                audience: TestJwtAudience,
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(JwtTokenExpiryMinutes),
                signingCredentials: credentials);

            // AuthService.cs line 159: serialize to compact format
            return new JwtSecurityTokenHandler().WriteToken(tokenDescriptor);
        }

        /// <summary>
        /// Generates a valid JWT token with custom claims provided by the caller.
        /// Uses the same signing key, issuer, audience, algorithm, and expiry as
        /// <see cref="GenerateJwtToken(Guid, string, string[])"/> but allows tests
        /// to specify arbitrary claims for edge case testing (e.g., missing claims,
        /// extra claims, invalid claim types).
        /// </summary>
        /// <param name="claims">Custom claims to include in the token.</param>
        /// <returns>A JWT token string in compact serialization format.</returns>
        public string GenerateJwtToken(IEnumerable<Claim> claims)
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(TestJwtKey));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256Signature);

            var tokenDescriptor = new JwtSecurityToken(
                issuer: TestJwtIssuer,
                audience: TestJwtAudience,
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(JwtTokenExpiryMinutes),
                signingCredentials: credentials);

            return new JwtSecurityTokenHandler().WriteToken(tokenDescriptor);
        }

        /// <summary>
        /// Generates an EXPIRED JWT token for testing JWT validation rejection.
        /// The token has an expiry of 30 minutes in the past, which should cause
        /// the JWT Bearer middleware to reject it with 401 Unauthorized
        /// (Startup.cs line 108: <c>ValidateLifetime = true</c>).
        /// </summary>
        /// <param name="userId">User ID for the NameIdentifier claim.</param>
        /// <param name="email">Email address for the Email claim.</param>
        /// <returns>An expired JWT token string in compact serialization format.</returns>
        public string GenerateExpiredJwtToken(Guid userId, string email)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, userId.ToString()),
                new Claim(ClaimTypes.Email, email)
            };

            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(TestJwtKey));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256Signature);

            var tokenDescriptor = new JwtSecurityToken(
                issuer: TestJwtIssuer,
                audience: TestJwtAudience,
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(-30), // Expired 30 minutes ago
                signingCredentials: credentials);

            return new JwtSecurityTokenHandler().WriteToken(tokenDescriptor);
        }
    }
}
