using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebVella.Erp.Service.Project.Database
{
    /// <summary>
    /// Represents a task record in the Project/Task microservice.
    /// Maps to the monolith's rec_task table, preserving all columns and
    /// application-set Guid primary keys (ValueGeneratedNever).
    /// Cross-service references (OwnerId, CreatedBy) are stored as plain UUIDs
    /// without foreign key constraints per AAP 0.7.1.
    ///
    /// Extracted from ProjectDbContext.cs to standalone domain entity file
    /// per DDD principles — domain entities belong in Domain/Entities/, not
    /// embedded in infrastructure code.
    ///
    /// Source: WebVella.Erp.Plugins.Next/NextPlugin.20190203.cs (task entity creation)
    ///         WebVella.Erp.Plugins.Next/NextPlugin.20190204.cs (field additions)
    ///         WebVella.Erp.Plugins.Next/NextPlugin.20190206.cs (field updates)
    /// </summary>
    [Table("rec_task")]
    public class TaskEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        /// <summary>Task subject/title — required field in the monolith.</summary>
        [Required]
        [Column("subject")]
        public string Subject { get; set; }

        /// <summary>HTML body content of the task.</summary>
        [Column("body")]
        public string Body { get; set; }

        /// <summary>
        /// Cross-service reference to the user who owns this task.
        /// Stored as UUID — NO FK constraint. Resolved via Core gRPC call.
        /// </summary>
        [Column("owner_id")]
        public Guid? OwnerId { get; set; }

        /// <summary>Task start date (nullable).</summary>
        [Column("start_date")]
        public DateTime? StartDate { get; set; }

        /// <summary>Task target/due date (nullable).</summary>
        [Column("target_date")]
        public DateTime? TargetDate { get; set; }

        /// <summary>Timestamp when the task was created.</summary>
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Cross-service reference to the user who created this task.
        /// Stored as UUID — NO FK constraint.
        /// </summary>
        [Column("created_by")]
        public Guid? CreatedBy { get; set; }

        /// <summary>Timestamp when the task was completed (nullable).</summary>
        [Column("completed_on")]
        public DateTime? CompletedOn { get; set; }

        /// <summary>
        /// Auto-incremented task number within scope.
        /// Stored as bigint in PostgreSQL.
        /// </summary>
        [Column("number")]
        public long Number { get; set; }

        /// <summary>Self-referencing parent task ID for task hierarchies.</summary>
        [Column("parent_id")]
        public Guid? ParentId { get; set; }

        /// <summary>FK to task_status entity — intra-service relation.</summary>
        [Column("status_id")]
        public Guid? StatusId { get; set; }

        /// <summary>FK to task_type entity — intra-service relation.</summary>
        [Column("type_id")]
        public Guid? TypeId { get; set; }

        /// <summary>
        /// Priority select field. Values: "1" (low), "2" (medium), "3" (high).
        /// Stored as text to match monolith SelectField behavior.
        /// </summary>
        [Column("priority")]
        public string Priority { get; set; }

        /// <summary>
        /// Aggregated non-billable time in minutes for this task.
        /// Monolith column: x_nonbillable_minutes (NumberField, decimal).
        /// </summary>
        [Column("x_nonbillable_minutes")]
        public decimal XNonbillableHours { get; set; }

        /// <summary>
        /// Aggregated billable time in minutes for this task.
        /// Monolith column: x_billable_minutes (NumberField, decimal).
        /// </summary>
        [Column("x_billable_minutes")]
        public decimal XBillableHours { get; set; }

        /// <summary>
        /// Scope identifier for multi-tenant/multi-project scoping.
        /// JSON array string, e.g. '["projects"]'.
        /// </summary>
        [Column("l_scope")]
        public string LScope { get; set; }

        /// <summary>
        /// JSON-encoded list of related record references.
        /// Used for cross-entity linking within the project domain.
        /// </summary>
        [Column("l_related_records")]
        public string LRelatedRecords { get; set; }

        /// <summary>
        /// Full-text search index field. Regenerated by SearchService
        /// to include denormalized data from related entities.
        /// </summary>
        [Column("x_search")]
        public string XSearch { get; set; }

        /// <summary>Reference to a recurrence plan (Ical.Net based).</summary>
        [Column("recurrence_id")]
        public Guid? RecurrenceId { get; set; }

        /// <summary>
        /// Human-readable task key (e.g., "PRJ-123").
        /// Composed from project abbreviation + task number.
        /// </summary>
        [Column("key")]
        public string Key { get; set; }

        // ----- Navigation properties (intra-service) -----

        /// <summary>Navigation to the task's status reference entity.</summary>
        public TaskStatusEntity Status { get; set; }

        /// <summary>Navigation to the task's type reference entity.</summary>
        public TaskTypeEntity Type { get; set; }

        /// <summary>Navigation to parent task (self-referencing).</summary>
        public TaskEntity Parent { get; set; }

        /// <summary>Child tasks in the task hierarchy.</summary>
        public ICollection<TaskEntity> Children { get; set; } = new List<TaskEntity>();

        /// <summary>M:N relation entries linking milestones to this task.</summary>
        public ICollection<MilestoneTaskRelation> MilestoneTaskRelations { get; set; } = new List<MilestoneTaskRelation>();

        /// <summary>M:N relation entries linking projects to this task.</summary>
        public ICollection<ProjectTaskRelation> ProjectTaskRelations { get; set; } = new List<ProjectTaskRelation>();
    }
}
